warning_ID: 179
warning_file_name: ArgumentParserImpl.java
warning_file_path: main/src/main/java/net/sourceforge/argparse4j/internal/ArgumentParserImpl.java
warning_repository_URL: https://github.com/argparse4j/argparse4j.git
warning_repository_commit: a0cef432451487d513382297cec2c5b14c147a30
warning_repository_name: argparse4j
warning_repository_target_java_version: '8'
warning_rule_key: S3358
warning_rule_name: Ternary operators should not be nested
warning_rule_type: Code_Smell
warning_specific_message: Extract this nested ternary operation into an independent
  statement.
warning_start_line: 899
