warning_ID: 21
warning_file_name: DefaultIntervalLoggerModel.java
warning_file_path: owasp-security-logging-common/src/main/java/org/owasp/security/logging/util/DefaultIntervalLoggerModel.java
warning_repository_URL: https://github.com/javabeanz/owasp-security-logging.git
warning_repository_commit: 35a674c9be1d751191f45ea2a89dd1c1ca7b4368
warning_repository_name: owasp-security-logging
warning_repository_target_java_version: '7'
warning_rule_key: S3014
warning_rule_name: '"ThreadGroup" should not be used'
warning_rule_type: Code_Smell
warning_specific_message: Remove this use of "ThreadGroup". Prefer the use of "ThreadPoolExecutor".
warning_start_line: 209
