warning_ID: 24
warning_file_name: ByteOffsetInputStream.java
warning_file_path: singer/src/main/java/com/pinterest/singer/reader/ByteOffsetInputStream.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S3551
warning_rule_name: Overrides should match their parent class methods in synchronization
warning_rule_type: Bug
warning_specific_message: Make this method "synchronized" to match the parent class
  implementation.
warning_start_line: 83
