warning_ID: 26
warning_file_name: DFAssinaturaDigital.java
warning_file_path: src/main/java/com/fincatto/documentofiscal/utils/DFAssinaturaDigital.java
warning_repository_URL: https://github.com/wmixvideo/nfe.git
warning_repository_commit: d0b2ce5ea0749448b1b3dbb9bef88d7eccd05240
warning_repository_name: nfe
warning_repository_target_java_version: '8'
warning_rule_key: S6377
warning_rule_name: XML signatures should be validated securely
warning_rule_type: Vulnerability
warning_specific_message: Set the 'org.jcp.xml.dsig.secureValidation' property to
  "true" on the 'DOMValidateContext' object to validate this XML signature securely.
warning_start_line: 57
