warning_ID: 34
warning_file_name: TripPattern.java
warning_file_path: src/main/java/org/opentripplanner/model/TripPattern.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1065
warning_rule_name: Unused labels should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused label.
warning_start_line: 433
