warning_ID: 35
warning_file_name: AbstractSolution.java
warning_file_path: jmetal-core/src/main/java/org/uma/jmetal/solution/AbstractSolution.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S2097
warning_rule_name: '"equals(Object obj)" should test argument type'
warning_rule_type: Bug
warning_specific_message: Add a type test to this method.
warning_start_line: 147
