warning_ID: 37
warning_file_name: ElevationModule.java
warning_file_path: src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S2445
warning_rule_name: Blocks should be synchronized on "private final" fields
warning_rule_type: Bug
warning_specific_message: '"graph" is a method parameter, and should not be used for
  synchronization.'
warning_start_line: 626
