warning_ID: 38
warning_file_name: Permission.java
warning_file_path: src/main/java/cn/nukkit/permission/Permission.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S2583
warning_rule_name: Conditionally executed code should be reachable
warning_rule_type: Bug
warning_specific_message: Change this condition so that it does not always evaluate
  to "true"
warning_start_line: 162
