warning_ID: 39
warning_file_name: Encryption.java
warning_file_path: watermark/src/main/java/me/superblaubeere27/obfuscator/watermark/Encryption.java
warning_repository_URL: https://github.com/superblaubeere27/obfuscator.git
warning_repository_commit: cc4421d7afe7aead7f59435b28aaba5bc69115b3
warning_repository_name: obfuscator
warning_repository_target_java_version: '8'
warning_rule_key: S5542
warning_rule_name: Encryption algorithms should be used with secure mode and padding
  scheme
warning_rule_type: Vulnerability
warning_specific_message: Use a secure padding scheme.
warning_start_line: 15
