warning_ID: 47
warning_file_name: SiriAlertsUpdateHandlerTest.java
warning_file_path: src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S5669
warning_rule_name: Vararg method arguments should not be confusing
warning_rule_type: Code_Smell
warning_specific_message: Cast this argument to 'String' to pass a single element
  to the vararg method.
warning_start_line: 738
