warning_ID: 48
warning_file_name: WithoutAlias.java
warning_file_path: src/test/benchmarks/org/mutabilitydetector/benchmarks/settermethod/singlecheck/WithoutAlias.java
warning_repository_URL: https://github.com/MutabilityDetector/MutabilityDetector.git
warning_repository_commit: ac1bc226e109b21bf92e74dd76d77e2f1a6a929d
warning_repository_name: MutabilityDetector
warning_repository_target_java_version: '8'
warning_rule_key: S2159
warning_rule_name: Silly equality checks should not be made
warning_rule_type: Bug
warning_specific_message: Remove this call to "equals"; comparisons between unrelated
  types always return false.
warning_start_line: 101
