warning_ID: 14
warning_file_name: ObjTreeTest.java
warning_file_path: src/test/java/org/nlpcn/commons/lang/tire/splitWord/ObjTreeTest.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S120
warning_rule_name: Package names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this package name to match the regular expression
  '^[a-z_]+(\.[a-z_][a-z0-9_]*)*$'.
warning_start_line: 1
