warning_ID: 15
warning_file_name: MojoToReportOptionsConverter.java
warning_file_path: pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java
warning_repository_URL: https://github.com/hcoles/pitest.git
warning_repository_commit: b3d752994e4e0234bb9494e739b1960240f1f9d3
warning_repository_name: pitest
warning_repository_target_java_version: '8'
warning_rule_key: S1612
warning_rule_name: Lambdas should be replaced with method references
warning_rule_type: Code_Smell
warning_specific_message: Replace this lambda with method reference 'File::new'.
warning_start_line: 326
