warning_ID: 19
warning_file_name: GtfsRealtime.java
warning_file_path: src/main/java/com/google/transit/realtime/GtfsRealtime.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1940
warning_rule_name: Boolean checks should not be inverted
warning_rule_type: Code_Smell
warning_specific_message: Use the opposite operator ("!=") instead.
warning_start_line: 19847
