warning_ID: 20
warning_file_name: GregorMutater.java
warning_file_path: pitest/src/main/java/org/pitest/mutationtest/engine/gregor/GregorMutater.java
warning_repository_URL: https://github.com/hcoles/pitest.git
warning_repository_commit: b3d752994e4e0234bb9494e739b1960240f1f9d3
warning_repository_name: pitest
warning_repository_target_java_version: '8'
warning_rule_key: S3655
warning_rule_name: Optional value should only be accessed after calling isPresent()
warning_rule_type: Bug
warning_specific_message: Call "bytes.isPresent()" before accessing the value.
warning_start_line: 100
