warning_ID: 3
warning_file_name: UF3.java
warning_file_path: jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/UF/UF3.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S3518
warning_rule_name: Zero should not be a possible denominator
warning_rule_type: Bug
warning_specific_message: Make sure this expression can't be zero before doing this
  division.
warning_start_line: 75
