warning_ID: 8
warning_file_name: Examples.java
warning_file_path: src/test/java/org/zeroturnaround/process/Examples.java
warning_repository_URL: https://github.com/zeroturnaround/zt-process-killer.git
warning_repository_commit: 6066bf2f98660429c6105350fff9b21cd07a00ef
warning_repository_name: zt-process-killer
warning_repository_target_java_version: '7'
warning_rule_key: S4036
warning_rule_name: Searching OS commands in PATH is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure the "PATH" used to find this command includes
  only what you intend.
warning_start_line: 37
