warning_ID: 9
warning_file_name: KeystoneUser.java
warning_file_path: core/src/main/java/org/openstack4j/openstack/identity/v3/domain/KeystoneUser.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S1206
warning_rule_name: '"equals(Object obj)" and "hashCode()" should be overridden in
  pairs'
warning_rule_type: Bug
warning_specific_message: This class overrides "equals()" and should therefore also
  override "hashCode()".
warning_start_line: 164
