warning_ID: 412
warning_file_name: CSSName.java
warning_file_path: openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/constants/CSSName.java
warning_repository_URL: https://github.com/danfickle/openhtmltopdf.git
warning_repository_commit: 0dcb7e4b8c80d0fbf6d21f970ccab7a701221b5d
warning_repository_name: openhtmltopdf
warning_repository_target_java_version: '8'
warning_rule_key: S1124
warning_rule_name: Modifiers should be declared in the correct order
warning_rule_type: Code_Smell
warning_specific_message: Reorder the modifiers to comply with the Java Language Specification.
warning_start_line: 1136
