warning_ID: 415
warning_file_name: XmlIOUtil.java
warning_file_path: protostuff-xml/src/main/java/io/protostuff/XmlIOUtil.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 578
