warning_ID: 427
warning_file_name: UpdateKnowledgeBase.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/servlet/setup/UpdateKnowledgeBase.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1075
warning_rule_name: URIs should not be hardcoded
warning_rule_type: Code_Smell
warning_specific_message: Refactor your code to get this URI from a customizable parameter.
warning_start_line: 79
