warning_ID: 432
warning_file_name: IsValidOp.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/operation/valid/IsValidOp.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1126
warning_rule_name: Return of boolean expressions should not be wrapped into an "if-then-else"
  statement
warning_rule_type: Code_Smell
warning_specific_message: Replace this if-then-else statement by a single return statement.
warning_start_line: 74
