warning_ID: 436
warning_file_name: LoginPacket.java
warning_file_path: src/main/java/cn/nukkit/network/protocol/LoginPacket.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S1186
warning_rule_name: Methods should not be empty
warning_rule_type: Code_Smell
warning_specific_message: Add a nested comment explaining why this method is empty,
  throw an UnsupportedOperationException or complete the implementation.
warning_start_line: 53
