warning_ID: 440
warning_file_name: FormatterTest.java
warning_file_path: core/src/test/java/com/google/googlejavaformat/java/FormatterTest.java
warning_repository_URL: https://github.com/google/google-java-format.git
warning_repository_commit: 93d649d0fbc07fc604f7b47b3098cf6e1df521de
warning_repository_name: google-java-format
warning_repository_target_java_version: '11'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "class
  Foo {\n" 4 times.
warning_start_line: 95
