warning_ID: 444
warning_file_name: EntityMinecartAbstract.java
warning_file_path: src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S1905
warning_rule_name: Redundant casts should not be used
warning_rule_type: Code_Smell
warning_specific_message: Remove this unnecessary cast to "double".
warning_start_line: 629
