warning_ID: 455
warning_file_name: TimeoutNacosConfigListener.java
warning_file_path: nacos-spring-context/src/main/java/com/alibaba/nacos/spring/context/event/config/TimeoutNacosConfigListener.java
warning_repository_URL: https://github.com/nacos-group/nacos-spring-project.git
warning_repository_commit: cddc2a329aca96b3ac483c2e1e24941101183789
warning_repository_name: nacos-spring-project
warning_repository_target_java_version: '6'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 72
