warning_ID: 458
warning_file_name: TestPodLogCycle.java
warning_file_path: singer/src/test/java/com/pinterest/singer/kubernetes/TestPodLogCycle.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S899
warning_rule_name: Return values should not be ignored when they contain the operation
  status code
warning_rule_type: Bug
warning_specific_message: Do something with the "boolean" value returned by "delete".
warning_start_line: 243
