warning_ID: 462
warning_file_name: VWSimplifierTest.java
warning_file_path: modules/core/src/test/java/org/locationtech/jts/simplify/VWSimplifierTest.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1118
warning_rule_name: Utility classes should not have public constructors
warning_rule_type: Code_Smell
warning_specific_message: Add a private constructor to hide the implicit public one.
warning_start_line: 73
