warning_ID: 475
warning_file_name: IntersectionVertexTest.java
warning_file_path: src/test/java/org/opentripplanner/routing/vertextype/IntersectionVertexTest.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S117
warning_rule_name: Local variable and method parameter names should comply with a
  naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this local variable to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 48
