warning_ID: 484
warning_file_name: SingerTestBase.java
warning_file_path: singer/src/test/java/com/pinterest/singer/SingerTestBase.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S1171
warning_rule_name: Only static class initializers should be used
warning_rule_type: Code_Smell
warning_specific_message: Move the contents of this initializer to a standard constructor
  or to field initializers.
warning_start_line: 262
