warning_ID: 485
warning_file_name: DisplayModelDaoJena.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/dao/jena/DisplayModelDaoJena.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 69
