warning_ID: 489
warning_file_name: SpacialMatch.java
warning_file_path: src/main/java/me/gosimple/nbvcxz/matching/match/SpacialMatch.java
warning_repository_URL: https://github.com/GoSimpleLLC/nbvcxz.git
warning_repository_commit: dc1c098a5d1725d94b8c019b3ccadcd9b3869862
warning_repository_name: nbvcxz
warning_repository_target_java_version: '7'
warning_rule_key: S117
warning_rule_name: Local variable and method parameter names should comply with a
  naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this local variable to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 32
