warning_ID: 494
warning_file_name: IntegrationTest.java
warning_file_path: dataenum-processor/src/test/java/com/spotify/dataenum/processor/IntegrationTest.java
warning_repository_URL: https://github.com/spotify/dataenum.git
warning_repository_commit: 7a91307ef55cf9ba94391a4572c9d68dba2c56d5
warning_repository_name: dataenum
warning_repository_target_java_version: '8'
warning_rule_key: S1130
warning_rule_name: '"throws" declarations should not be superfluous'
warning_rule_type: Code_Smell
warning_specific_message: Remove the declaration of thrown exception 'java.lang.Exception',
  as it cannot be thrown from method's body.
warning_start_line: 101
