warning_ID: 512
warning_file_name: Tuple7.java
warning_file_path: src/main/java/com/github/davidmoten/rx/jdbc/tuple/Tuple7.java
warning_repository_URL: https://github.com/davidmoten/rxjava-jdbc.git
warning_repository_commit: e62609a10fb144debd2b3b833f02474c01cc5b81
warning_repository_name: rxjava-jdbc
warning_repository_target_java_version: '7'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 93
