warning_ID: 518
warning_file_name: CollectionFieldTest.java
warning_file_path: src/test/java/org/mutabilitydetector/checkers/CollectionFieldTest.java
warning_repository_URL: https://github.com/MutabilityDetector/MutabilityDetector.git
warning_repository_commit: ac1bc226e109b21bf92e74dd76d77e2f1a6a929d
warning_repository_name: MutabilityDetector
warning_repository_target_java_version: '8'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 9
