warning_ID: 524
warning_file_name: ChartForDynamicProblemsContainer.java
warning_file_path: jmetal-core/src/main/java/org/uma/jmetal/util/chartcontainer/ChartForDynamicProblemsContainer.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 91
