warning_ID: 527
warning_file_name: MongoV4_0QueryConverterIT.java
warning_file_path: src/test/java/com/github/vincentrussell/query/mongodb/sql/converter/MongoV4_0QueryConverterIT.java
warning_repository_URL: https://github.com/vincentrussell/sql-to-mongo-db-query-converter.git
warning_repository_commit: 961f5c04ef387ee88086908ebacdfb6ef6e3081a
warning_repository_name: sql-to-mongo-db-query-converter
warning_repository_target_java_version: '7'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "\t}\n"
  3 times.
warning_start_line: 119
