warning_ID: 541
warning_file_name: ProcessSparqlDataGetterN3.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/preprocessors/utils/ProcessSparqlDataGetterN3.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S5361
warning_rule_name: '"String#replace" should be preferred to "String#replaceAll"'
warning_rule_type: Code_Smell
warning_specific_message: Replace this call to "replaceAll()" by a call to the "replace()"
  method.
warning_start_line: 199
