warning_ID: 546
warning_file_name: PersistentVector.java
warning_file_path: src/main/java/org/organicdesign/fp/collections/PersistentVector.java
warning_repository_URL: https://github.com/GlenKPeterson/Paguro.git
warning_repository_commit: de98375df2dd9c26a8cb618d51862f52c64602af
warning_repository_name: Paguro
warning_repository_target_java_version: '11'
warning_rule_key: S2065
warning_rule_name: Fields in non-serializable classes should not be "transient"
warning_rule_type: Code_Smell
warning_specific_message: Remove the "transient" modifier from this field.
warning_start_line: 72
