warning_ID: 547
warning_file_name: MenuManagementEdit.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/edit/MenuManagementEdit.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1124
warning_rule_name: Modifiers should be declared in the correct order
warning_rule_type: Code_Smell
warning_specific_message: Reorder the modifiers to comply with the Java Language Specification.
warning_start_line: 39
