warning_ID: 557
warning_file_name: MwLocalDumpFileTest.java
warning_file_path: wdtk-dumpfiles/src/test/java/org/wikidata/wdtk/dumpfiles/MwLocalDumpFileTest.java
warning_repository_URL: https://github.com/Wikidata/Wikidata-Toolkit.git
warning_repository_commit: 8400cdd50528f0d21eea93bacf5998ba950b30ce
warning_repository_name: Wikidata-Toolkit
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "testdump-20150512.json.gz"
  4 times.
warning_start_line: 66
