warning_ID: 566
warning_file_name: TestTable.java
warning_file_path: ascii-render/src/test/java/com/indvd00m/ascii/render/tests/TestTable.java
warning_repository_URL: https://github.com/indvd00m/java-ascii-render.git
warning_repository_commit: 611c08cef73367d6f6d20eb4f8f4721f917a42c6
warning_repository_name: java-ascii-render
warning_repository_target_java_version: '6'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 174
