warning_ID: 580
warning_file_name: SelectionTest.java
warning_file_path: license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/util/SelectionTest.java
warning_repository_URL: https://github.com/mycila/license-maven-plugin.git
warning_repository_commit: 690a43fac1629c2e1f8be424e3b658d92496bfdf
warning_repository_name: license-maven-plugin
warning_repository_target_java_version: '8'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 113
