warning_ID: 583
warning_file_name: SmartGetWordTest.java
warning_file_path: src/test/java/org/nlpcn/commons/lang/tire/splitWord/SmartGetWordTest.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 41
