warning_ID: 590
warning_file_name: MovsimCoreMain.java
warning_file_path: core/src/main/java/org/movsim/MovsimCoreMain.java
warning_repository_URL: https://github.com/movsim/movsim.git
warning_repository_commit: 24d4f4b83a7d2e14f16419fbf7ce05cb019c8066
warning_repository_name: movsim
warning_repository_target_java_version: '8'
warning_rule_key: S1134
warning_rule_name: Track uses of "FIXME" tags
warning_rule_type: Code_Smell
warning_specific_message: Take the required action to fix the issue indicated by this
  comment.
warning_start_line: 64
