warning_ID: 596
warning_file_name: AbstractRecorderMaintainer.java
warning_file_path: MyPerf4J-Core/src/main/java/cn/myperf4j/core/recorder/AbstractRecorderMaintainer.java
warning_repository_URL: https://github.com/LinShunKang/MyPerf4J.git
warning_repository_commit: caed27c4e35d7ba6841024a8a58c5ed33079ddfb
warning_repository_name: MyPerf4J
warning_repository_target_java_version: '7'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 88
