warning_ID: 608
warning_file_name: ST_InteriorRingN.java
warning_file_path: hive/src/main/java/com/esri/hadoop/hive/ST_InteriorRingN.java
warning_repository_URL: https://github.com/Esri/spatial-framework-for-hadoop.git
warning_repository_commit: 28cc6ab472711da6c2124ad22bd33caa8a78c77c
warning_repository_name: spatial-framework-for-hadoop
warning_repository_target_java_version: '6'
warning_rule_key: S101
warning_rule_name: Class names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.
warning_start_line: 33
