warning_ID: 612
warning_file_name: RelationalOperations.java
warning_file_path: src/main/java/com/esri/core/geometry/RelationalOperations.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S1659
warning_rule_name: Multiple variables should not be declared on the same line
warning_rule_type: Code_Smell
warning_specific_message: Declare "env_b" and all following declarations on a separate
  line.
warning_start_line: 340
