warning_ID: 613
warning_file_name: ReadOnlyMemMap.java
warning_file_path: src/main/java/com/spotify/sparkey/ReadOnlyMemMap.java
warning_repository_URL: https://github.com/spotify/sparkey-java.git
warning_repository_commit: c829bab45abf9cba3d017b798efe9ef5f0effbb3
warning_repository_name: sparkey-java
warning_repository_target_java_version: '8'
warning_rule_key: S1170
warning_rule_name: Public constants and fields initialized at declaration should be
  "static final" rather than merely "final"
warning_rule_type: Code_Smell
warning_specific_message: Make this final field static too.
warning_start_line: 34
