warning_ID: 617
warning_file_name: ExamplesTest.java
warning_file_path: src/test/java/com/sonalake/utah/ExamplesTest.java
warning_repository_URL: https://github.com/sonalake/utah-parser.git
warning_repository_commit: 65467f2ad877018be9b0ae720e453a5a041a8901
warning_repository_name: utah-parser
warning_repository_target_java_version: '8'
warning_rule_key: S1130
warning_rule_name: '"throws" declarations should not be superfluous'
warning_rule_type: Code_Smell
warning_specific_message: Remove the redundant 'java.io.IOException' thrown exception
  declaration(s).
warning_start_line: 131
