warning_ID: 622
warning_file_name: ANNIndex.java
warning_file_path: src/main/java/com/spotify/annoy/ANNIndex.java
warning_repository_URL: https://github.com/spotify/annoy-java.git
warning_repository_commit: aef275bd5b872b0931bde557bf8627c0476246af
warning_repository_name: annoy-java
warning_repository_target_java_version: '8'
warning_rule_key: S112
warning_rule_name: Generic exceptions should never be thrown
warning_rule_type: Code_Smell
warning_specific_message: Define and throw a dedicated exception instead of using
  a generic one.
warning_start_line: 282
