warning_ID: 623
warning_file_name: MediaInfoDocumentImplTest.java
warning_file_path: wdtk-datamodel/src/test/java/org/wikidata/wdtk/datamodel/implementation/MediaInfoDocumentImplTest.java
warning_repository_URL: https://github.com/Wikidata/Wikidata-Toolkit.git
warning_repository_commit: 8400cdd50528f0d21eea93bacf5998ba950b30ce
warning_repository_name: Wikidata-Toolkit
warning_repository_target_java_version: '8'
warning_rule_key: S1170
warning_rule_name: Public constants and fields initialized at declaration should be
  "static final" rather than merely "final"
warning_rule_type: Code_Smell
warning_specific_message: Make this final field static too.
warning_start_line: 57
