warning_ID: 627
warning_file_name: JoinE2eTest.java
warning_file_path: src/test/java/net/kaczmarzyk/JoinE2eTest.java
warning_repository_URL: https://github.com/tkaczmarzyk/specification-arg-resolver.git
warning_repository_commit: 52fe8d284f687ec86fea91b48f47d61dc6b32510
warning_repository_name: specification-arg-resolver
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "/join/customers"
  4 times.
warning_start_line: 122
