warning_ID: 639
warning_file_name: HostSourceDirective.java
warning_file_path: src/main/java/com/shapesecurity/salvation2/Directives/HostSourceDirective.java
warning_repository_URL: https://github.com/shapesecurity/salvation.git
warning_repository_commit: e2b07ea083e1c15415a25391c95c604a23ec9bfb
warning_repository_name: salvation
warning_repository_target_java_version: '8'
warning_rule_key: S3776
warning_rule_name: Cognitive Complexity of methods should not be too high
warning_rule_type: Code_Smell
warning_specific_message: Refactor this method to reduce its Cognitive Complexity
  from 22 to the 15 allowed.
warning_start_line: 60
