warning_ID: 662
warning_file_name: TestOGC.java
warning_file_path: src/test/java/com/esri/core/geometry/TestOGC.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S1199
warning_rule_name: Nested code blocks should not be used
warning_rule_type: Code_Smell
warning_specific_message: Extract this nested code block into a method.
warning_start_line: 743
