warning_ID: 693
warning_file_name: Unsafe.java
warning_file_path: src/test/benchmarks/org/mutabilitydetector/benchmarks/escapedthis/Unsafe.java
warning_repository_URL: https://github.com/MutabilityDetector/MutabilityDetector.git
warning_repository_commit: ac1bc226e109b21bf92e74dd76d77e2f1a6a929d
warning_repository_name: MutabilityDetector
warning_repository_target_java_version: '8'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 96
