warning_ID: 694
warning_file_name: AuditableLogbackThriftLoggerTest.java
warning_file_path: thrift-logger/src/test/java/com/pinterest/singer/client/AuditableLogbackThriftLoggerTest.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S1481
warning_rule_name: Unused local variables should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused "der" local variable.
warning_start_line: 222
