warning_ID: 695
warning_file_name: MOEADDRA.java
warning_file_path: jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/moead/MOEADDRA.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S1659
warning_rule_name: Multiple variables should not be declared on the same line
warning_rule_type: Code_Smell
warning_specific_message: Declare "f2" and all following declarations on a separate
  line.
warning_start_line: 105
