warning_ID: 697
warning_file_name: HttpTemplate.java
warning_file_path: src/main/java/si/mazi/rescu/HttpTemplate.java
warning_repository_URL: https://github.com/mmazi/rescu.git
warning_repository_commit: 963e5c2c00ad4a521e0b1876e2aade2cf84866f8
warning_repository_name: rescu
warning_repository_target_java_version: '8'
warning_rule_key: S108
warning_rule_name: Nested blocks of code should not be left empty
warning_rule_type: Code_Smell
warning_specific_message: Either remove or fill this block of code.
warning_start_line: 262
