warning_ID: 168
warning_file_name: FilteringIterable.java
warning_file_path: src/main/java/com/jnape/palatable/lambda/internal/iteration/FilteringIterable.java
warning_repository_URL: https://github.com/palatable/lambda.git
warning_repository_commit: 3f23529573f7a2f7f7a11aca3d9d7e720cf2a15b
warning_repository_name: lambda
warning_repository_target_java_version: '8'
warning_rule_key: S4968
warning_rule_name: The upper bound of type variables and wildcards should not be "final"
warning_rule_type: Code_Smell
warning_specific_message: Replace this type parametrization by the 'final' type `Boolean`.
warning_start_line: 17
