warning_ID: 186
warning_file_name: AdaptedJUnitTestUnit.java
warning_file_path: pitest/src/main/java/org/pitest/junit/adapter/AdaptedJUnitTestUnit.java
warning_repository_URL: https://github.com/hcoles/pitest.git
warning_repository_commit: b3d752994e4e0234bb9494e739b1960240f1f9d3
warning_repository_name: pitest
warning_repository_target_java_version: '8'
warning_rule_key: S2139
warning_rule_name: Exceptions should be either logged or rethrown but not both
warning_rule_type: Code_Smell
warning_specific_message: Either log this exception and handle it, or rethrow it with
  some contextual information.
warning_start_line: 108
