warning_ID: 192
warning_file_name: MinimumBoundingCircleStressTest.java
warning_file_path: modules/core/src/test/java/test/jts/perf/algorithm/MinimumBoundingCircleStressTest.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1197
warning_rule_name: Array designators "[]" should be on the type, not the variable
warning_rule_type: Code_Smell
warning_specific_message: Move the array designators [] to the type.
warning_start_line: 25
