warning_ID: 553
warning_file_name: Issue190Test.java
warning_file_path: src/test/java/net/jodah/failsafe/issues/Issue190Test.java
warning_repository_URL: https://github.com/jhalterman/failsafe.git
warning_repository_commit: f9ddba08a7b218c0f14dc8f713709b2e28aeab65
warning_repository_name: failsafe
warning_repository_target_java_version: '8'
warning_rule_key: S1602
warning_rule_name: Lambdas containing only one statement should not nest this statement
  in a block
warning_rule_type: Code_Smell
warning_specific_message: Remove useless curly braces around statement
warning_start_line: 42
