warning_ID: 555
warning_file_name: RuntimeEnv.java
warning_file_path: protostuff-runtime-md/src/main/java/io/protostuff/runtime/RuntimeEnv.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S2147
warning_rule_name: Catches should be combined
warning_rule_type: Code_Smell
warning_specific_message: Combine this catch with the one at line 389, which has the
  same body.
warning_start_line: 393
