warning_ID: 558
warning_file_name: MDFeConsultaStub.java
warning_file_path: src/main/java/com/fincatto/documentofiscal/mdfe3/webservices/consulta/MDFeConsultaStub.java
warning_repository_URL: https://github.com/wmixvideo/nfe.git
warning_repository_commit: d0b2ce5ea0749448b1b3dbb9bef88d7eccd05240
warning_repository_name: nfe
warning_repository_target_java_version: '8'
warning_rule_key: S3776
warning_rule_name: Cognitive Complexity of methods should not be too high
warning_rule_type: Code_Smell
warning_specific_message: Refactor this method to reduce its Cognitive Complexity
  from 22 to the 15 allowed.
warning_start_line: 551
