warning_ID: 564
warning_file_name: PipelineListener.java
warning_file_path: src/main/java/in/ashwanthkumar/gocd/slack/PipelineListener.java
warning_repository_URL: https://github.com/ashwanthkumar/gocd-slack-build-notifier.git
warning_repository_commit: 4c4c7065b662444b714c60a508bb873117909ed6
warning_repository_name: gocd-slack-build-notifier
warning_repository_target_java_version: '11'
warning_rule_key: S116
warning_rule_name: Field names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this field "LOG" to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 12
