warning_ID: 574
warning_file_name: JDBC4ResultSet.java
warning_file_path: src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java
warning_repository_URL: https://github.com/xerial/sqlite-jdbc.git
warning_repository_commit: 6ca62fd07bf7faf58e923ba8651757621ffc693c
warning_repository_name: sqlite-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S1135
warning_rule_name: Track uses of "TODO" tags
warning_rule_type: Code_Smell
warning_specific_message: Complete the task associated to this TODO comment.
warning_start_line: 234
