warning_ID: 576
warning_file_name: TER.java
warning_file_path: src/main/java/org/apache/joshua/metrics/TER.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S899
warning_rule_name: Return values should not be ignored when they contain the operation
  status code
warning_rule_type: Bug
warning_specific_message: Do something with the "boolean" value returned by "delete".
warning_start_line: 271
