warning_ID: 586
warning_file_name: DexClassStruct.java
warning_file_path: src/main/java/net/dongliu/apk/parser/struct/dex/DexClassStruct.java
warning_repository_URL: https://github.com/hsiafan/apk-parser.git
warning_repository_commit: 4d5a08e4d28fa2fce7fa356394c62c5e51a192e2
warning_repository_name: apk-parser
warning_repository_target_java_version: '7'
warning_rule_key: S3008
warning_rule_name: Static non-final field names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this field "ACC_NATIVE" to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 36
