warning_ID: 624
warning_file_name: NettyResponseUtil.java
warning_file_path: src/main/java/io/github/hapjava/server/impl/http/impl/NettyResponseUtil.java
warning_repository_URL: https://github.com/hap-java/HAP-Java.git
warning_repository_commit: f2f93cc29321fb117216466430ceec93b3a2780e
warning_repository_name: HAP-Java
warning_repository_target_java_version: '8'
warning_rule_key: S1118
warning_rule_name: Utility classes should not have public constructors
warning_rule_type: Code_Smell
warning_specific_message: Add a private constructor to hide the implicit public one.
warning_start_line: 12
