warning_ID: 625
warning_file_name: GroupPermissionServiceTest.java
warning_file_path: src/test/java/ru/org/linux/topic/GroupPermissionServiceTest.java
warning_repository_URL: https://github.com/maxcom/lorsource.git
warning_repository_commit: d195bea72c60acd4a0f4ec48a7374ca4ea6c47d8
warning_repository_name: lorsource
warning_repository_target_java_version: '8'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 328
