warning_ID: 630
warning_file_name: TableTestReport.java
warning_file_path: src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/TableTestReport.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1118
warning_rule_name: Utility classes should not have public constructors
warning_rule_type: Code_Smell
warning_specific_message: Add a private constructor to hide the implicit public one.
warning_start_line: 20
