warning_ID: 637
warning_file_name: GeometryOverlay.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/geom/GeometryOverlay.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1764
warning_rule_name: Identical expressions should not be used on both sides of a binary
  operator
warning_rule_type: Bug
warning_specific_message: Correct one of the identical sub-expressions on both sides
  of operator "||"
warning_start_line: 143
