warning_ID: 638
warning_file_name: Ngram.java
warning_file_path: src/main/java/org/apache/joshua/util/Ngram.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S1135
warning_rule_name: Track uses of "TODO" tags
warning_rule_type: Code_Smell
warning_specific_message: Complete the task associated to this TODO comment.
warning_start_line: 78
