warning_ID: 641
warning_file_name: LoadMessageInterface.java
warning_file_path: MSGViewer/src/main/java/net/sourceforge/MSGViewer/LoadMessageInterface.java
warning_repository_URL: https://github.com/lolo101/MsgViewer.git
warning_repository_commit: 42266b9a62ec9706b1042f118fd6f57c6f074fd2
warning_repository_name: MsgViewer
warning_repository_target_java_version: '11'
warning_rule_key: S120
warning_rule_name: Package names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this package name to match the regular expression
  '^[a-z_]+(\.[a-z_][a-z0-9_]*)*$'.
warning_start_line: 6
