warning_ID: 643
warning_file_name: VueComponent.java
warning_file_path: core/src/main/java/com/axellience/vuegwt/core/client/component/VueComponent.java
warning_repository_URL: https://github.com/VueGWT/vue-gwt.git
warning_repository_commit: dc818e0ac31c4fd4254065b50a1d7c59f291ca9d
warning_repository_name: vue-gwt
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 118
