warning_ID: 661
warning_file_name: JavadocFormatter.java
warning_file_path: core/src/main/java/com/google/googlejavaformat/java/javadoc/JavadocFormatter.java
warning_repository_URL: https://github.com/google/google-java-format.git
warning_repository_commit: 93d649d0fbc07fc604f7b47b3098cf6e1df521de
warning_repository_name: google-java-format
warning_repository_target_java_version: '11'
warning_rule_key: S1135
warning_rule_name: Track uses of "TODO" tags
warning_rule_type: Code_Smell
warning_specific_message: Complete the task associated to this TODO comment.
warning_start_line: 142
