warning_ID: 664
warning_file_name: StringSerializer.java
warning_file_path: protostuff-api/src/main/java/io/protostuff/StringSerializer.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S107
warning_rule_name: Methods should not have too many parameters
warning_rule_type: Code_Smell
warning_specific_message: Method has 8 parameters, which is greater than 7 authorized.
warning_start_line: 340
