warning_ID: 674
warning_file_name: StreamedStringSerializer.java
warning_file_path: protostuff-api/src/main/java/io/protostuff/StreamedStringSerializer.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S1659
warning_rule_name: Multiple variables should not be declared on the same line
warning_rule_type: Code_Smell
warning_specific_message: Declare "withIntOffset" on a separate line.
warning_start_line: 367
