warning_ID: 103
warning_file_name: IOHelper.java
warning_file_path: robot-core/src/main/java/org/obolibrary/robot/IOHelper.java
warning_repository_URL: https://github.com/ontodev/robot.git
warning_repository_commit: 8a9313440fb18819dd4db29b9bae6da435e9dc74
warning_repository_name: robot
warning_repository_target_java_version: '8'
warning_rule_key: S5996
warning_rule_name: Regex boundaries should not be used in a way that can never be
  matched
warning_rule_type: Bug
warning_specific_message: Remove or replace this boundary that will never match because
  it appears before mandatory input.
warning_start_line: 736
