warning_ID: 104
warning_file_name: PageElementPosition.java
warning_file_path: openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/constants/PageElementPosition.java
warning_repository_URL: https://github.com/danfickle/openhtmltopdf.git
warning_repository_commit: 0dcb7e4b8c80d0fbf6d21f970ccab7a701221b5d
warning_repository_name: openhtmltopdf
warning_repository_target_java_version: '8'
warning_rule_key: S4201
warning_rule_name: Null checks should not be used with "instanceof"
warning_rule_type: Code_Smell
warning_specific_message: Remove this unnecessary null check; "instanceof" returns
  false for nulls.
warning_start_line: 65
