warning_ID: 106
warning_file_name: FileOptionCompleterTest.java
warning_file_path: aesh/src/test/java/org/aesh/command/completer/FileOptionCompleterTest.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S5443
warning_rule_name: Using publicly writable directories is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure publicly writable directories are used safely
  here.
warning_start_line: 57
