warning_ID: 111
warning_file_name: LoggingCallsFilterTest.java
warning_file_path: pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/logging/LoggingCallsFilterTest.java
warning_repository_URL: https://github.com/hcoles/pitest.git
warning_repository_commit: b3d752994e4e0234bb9494e739b1960240f1f9d3
warning_repository_name: pitest
warning_repository_target_java_version: '8'
warning_rule_key: S2123
warning_rule_name: Values should not be uselessly incremented
warning_rule_type: Bug
warning_specific_message: Remove this increment or correct the code not to waste it.
warning_start_line: 116
