warning_ID: 112
warning_file_name: EncodingDetectorInputStream.java
warning_file_path: src/main/java/org/mozilla/universalchardet/EncodingDetectorInputStream.java
warning_repository_URL: https://github.com/albfernandez/juniversalchardet.git
warning_repository_commit: 30f7ac3a6c6f7465e00e20c98a20429654c49160
warning_repository_name: juniversalchardet
warning_repository_target_java_version: '7'
warning_rule_key: S4517
warning_rule_name: InputSteam.read() implementation should not return a signed byte
warning_rule_type: Bug
warning_specific_message: Convert this signed byte into an unsigned byte.
warning_start_line: 71
