warning_ID: 113
warning_file_name: PolymorphicMapSchema.java
warning_file_path: protostuff-runtime/src/main/java/io/protostuff/runtime/PolymorphicMapSchema.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S1596
warning_rule_name: '"Collections.EMPTY_LIST", "EMPTY_MAP", and "EMPTY_SET" should
  not be used'
warning_rule_type: Code_Smell
warning_specific_message: Replace "Collections.EMPTY_MAP" by "Collections.emptyMap()".
warning_start_line: 320
