warning_ID: 115
warning_file_name: PropComponentExposedType.java
warning_file_path: processors/src/test/resources/props/compileresult/PropComponentExposedType.java
warning_repository_URL: https://github.com/VueGWT/vue-gwt.git
warning_repository_commit: dc818e0ac31c4fd4254065b50a1d7c59f291ca9d
warning_repository_name: vue-gwt
warning_repository_target_java_version: '8'
warning_rule_key: S1598
warning_rule_name: Package declaration should match source file directory
warning_rule_type: Code_Smell
warning_specific_message: This file "PropComponentExposedType.java" should be located
  in "props" directory, not in "/workspaces/master-thesis-pascal-joos/code_cure_agent/experimental_setups/evaluation_dataset/./temp/processors/src/test/resources/props/compileresult".
warning_start_line: 1
