warning_ID: 118
warning_file_name: SmartForest.java
warning_file_path: src/main/java/org/nlpcn/commons/lang/tire/domain/SmartForest.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S4351
warning_rule_name: '"compareTo" should not be overloaded'
warning_rule_type: Bug
warning_specific_message: Refactor this method so that its argument is of type 'SmartForest'.
warning_start_line: 138
