warning_ID: 125
warning_file_name: VoronoiTest.java
warning_file_path: modules/core/src/test/java/org/locationtech/jts/triangulate/VoronoiTest.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S2259
warning_rule_name: Null pointers should not be dereferenced
warning_rule_type: Bug
warning_specific_message: A "NullPointerException" could be thrown; "result" is nullable
  here.
warning_start_line: 80
