warning_ID: 126
warning_file_name: Watchdog.java
warning_file_path: src/main/java/cn/nukkit/utils/Watchdog.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S2236
warning_rule_name: Methods "wait(...)", "notify()" and "notifyAll()" should not be
  called on Thread instances
warning_rule_type: Bug
warning_specific_message: Refactor the synchronisation mechanism to not use a Thread
  instance as a monitor
warning_start_line: 25
