warning_ID: 137
warning_file_name: TranslationResponseStream.java
warning_file_path: src/main/java/org/apache/joshua/decoder/TranslationResponseStream.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S2446
warning_rule_name: '"notifyAll" should be used'
warning_rule_type: Bug
warning_specific_message: '"notify" may not wake up the appropriate thread.'
warning_start_line: 99
