warning_ID: 146
warning_file_name: ComponentExposedTypeGenerator.java
warning_file_path: processors/src/main/java/com/axellience/vuegwt/processors/component/ComponentExposedTypeGenerator.java
warning_repository_URL: https://github.com/VueGWT/vue-gwt.git
warning_repository_commit: dc818e0ac31c4fd4254065b50a1d7c59f291ca9d
warning_repository_name: vue-gwt
warning_repository_target_java_version: '8'
warning_rule_key: S3864
warning_rule_name: '"Stream.peek" should be used with caution'
warning_rule_type: Code_Smell
warning_specific_message: Remove this use of "Stream.peek".
warning_start_line: 578
