warning_ID: 149
warning_file_name: BanIpCommand.java
warning_file_path: src/main/java/cn/nukkit/command/defaults/BanIpCommand.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S6353
warning_rule_name: Regular expression quantifiers and character classes should be
  used concisely
warning_rule_type: Code_Smell
warning_specific_message: Use concise character class syntax '\\d' instead of '[0-9]'.
warning_start_line: 64
