warning_ID: 151
warning_file_name: NameValuePair.java
warning_file_path: src/main/java/com/lmax/simpledsl/NameValuePair.java
warning_repository_URL: https://github.com/LMAX-Exchange/Simple-DSL.git
warning_repository_commit: 73abdb21ddcfa2321da7ae43fc5df93b843568f4
warning_repository_name: Simple-DSL
warning_repository_target_java_version: '8'
warning_rule_key: S6035
warning_rule_name: Single-character alternations in regular expressions should be
  replaced with character classes
warning_rule_type: Code_Smell
warning_specific_message: Replace this alternation with a character class.
warning_start_line: 20
