warning_ID: 152
warning_file_name: JavaScriptValidatorTest.java
warning_file_path: redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
warning_repository_URL: https://github.com/redpen-cc/redpen.git
warning_repository_commit: cce87e790828cb88dd5c3bfbdcb117d351eb6bbd
warning_repository_name: redpen
warning_repository_target_java_version: '8'
warning_rule_key: S899
warning_rule_name: Return values should not be ignored when they contain the operation
  status code
warning_rule_type: Bug
warning_specific_message: Do something with the "boolean" value returned by "delete".
warning_start_line: 267
