warning_ID: 155
warning_file_name: DateHeader.java
warning_file_path: MSGViewer/src/main/java/net/sourceforge/MSGViewer/factory/mbox/headers/DateHeader.java
warning_repository_URL: https://github.com/lolo101/MsgViewer.git
warning_repository_commit: 42266b9a62ec9706b1042f118fd6f57c6f074fd2
warning_repository_name: MsgViewer
warning_repository_target_java_version: '11'
warning_rule_key: S2885
warning_rule_name: Non-thread-safe fields should not be static
warning_rule_type: Bug
warning_specific_message: Make "date_format" an instance variable.
warning_start_line: 35
