warning_ID: 160
warning_file_name: SparkeyLogIterator.java
warning_file_path: src/main/java/com/spotify/sparkey/SparkeyLogIterator.java
warning_repository_URL: https://github.com/spotify/sparkey-java.git
warning_repository_commit: c829bab45abf9cba3d017b798efe9ef5f0effbb3
warning_repository_name: sparkey-java
warning_repository_target_java_version: '8'
warning_rule_key: S2674
warning_rule_name: The value returned from a stream read should be checked
warning_rule_type: Bug
warning_specific_message: Check the return value of the "read" call to see how many
  bytes were read.
warning_start_line: 235
