warning_ID: 954
warning_file_name: DatabaseCreator.java
warning_file_path: src/test/java/com/github/davidmoten/rx/jdbc/DatabaseCreator.java
warning_repository_URL: https://github.com/davidmoten/rxjava-jdbc.git
warning_repository_commit: e62609a10fb144debd2b3b833f02474c01cc5b81
warning_repository_name: rxjava-jdbc
warning_repository_target_java_version: '7'
warning_rule_key: S2095
warning_rule_name: Resources should be closed
warning_rule_type: Bug
warning_specific_message: Use try-with-resources or close this "PreparedStatement"
  in a "finally" clause.
warning_start_line: 78
