warning_ID: 961
warning_file_name: HooksTest.java
warning_file_path: src/test/java/io/gsonfire/gson/HooksTest.java
warning_repository_URL: https://github.com/julman99/gson-fire.git
warning_repository_commit: 5dd4cd703065b0d4127390c6bdec1fb434ebec71
warning_repository_name: gson-fire
warning_repository_target_java_version: '6'
warning_rule_key: S1700
warning_rule_name: A field should not duplicate the name of its containing class
warning_rule_type: Code_Smell
warning_specific_message: Rename field "b"
warning_start_line: 158
