warning_ID: 977
warning_file_name: ProvidesSupplierWiringTests.java
warning_file_path: src/test/java/org/springframework/guice/ProvidesSupplierWiringTests.java
warning_repository_URL: https://github.com/spring-projects/spring-guice.git
warning_repository_commit: ebfdb1be8eabafc55d0007ff2ec194ddc6f6f15c
warning_repository_name: spring-guice
warning_repository_target_java_version: '8'
warning_rule_key: S1612
warning_rule_name: Lambdas should be replaced with method references
warning_rule_type: Code_Smell
warning_specific_message: Replace this lambda with method reference 'Bar::new'.
warning_start_line: 73
