warning_ID: 983
warning_file_name: FunctionUtils.java
warning_file_path: src/main/java/org/organicdesign/fp/FunctionUtils.java
warning_repository_URL: https://github.com/GlenKPeterson/Paguro.git
warning_repository_commit: de98375df2dd9c26a8cb618d51862f52c64602af
warning_repository_name: Paguro
warning_repository_target_java_version: '11'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 39
