warning_ID: 989
warning_file_name: BaseFunctionHandler.java
warning_file_path: src/main/java/org/torpedoquery/jpa/internal/handlers/BaseFunctionHandler.java
warning_repository_URL: https://github.com/xjodoin/torpedoquery.git
warning_repository_commit: da8b5ad47115375a40d9a9b059cbfee615eb41ca
warning_repository_name: torpedoquery
warning_repository_target_java_version: '8'
warning_rule_key: S1450
warning_rule_name: Private fields only used as local variables in methods should become
  local variables
warning_rule_type: Code_Smell
warning_specific_message: Remove the "queryBuilder" field and declare it as a local
  variable in the relevant methods.
warning_start_line: 37
