warning_ID: 990
warning_file_name: CommandLinePopulatorTest.java
warning_file_path: aesh/src/test/java/org/aesh/command/populator/CommandLinePopulatorTest.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "myoption"
  6 times.
warning_start_line: 426
