warning_ID: 996
warning_file_name: PiwikRequest.java
warning_file_path: src/main/java/org/piwik/java/tracking/PiwikRequest.java
warning_repository_URL: https://github.com/matomo-org/matomo-java-tracker.git
warning_repository_commit: a1dbaae91944c5185da03c5b67e2640a7349a4c4
warning_repository_name: matomo-java-tracker
warning_repository_target_java_version: '8'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 1711
