warning_ID: 997
warning_file_name: JTSOpCmdTest.java
warning_file_path: modules/app/src/test/java/org/locationtech/jtstest/cmd/JTSOpCmdTest.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "Incorrect
  summary value for arg values" 3 times.
warning_start_line: 150
