warning_ID: 746
warning_file_name: GeoJsonCrsTables.java
warning_file_path: src/main/java/com/esri/core/geometry/GeoJsonCrsTables.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S1905
warning_rule_name: Redundant casts should not be used
warning_rule_type: Code_Smell
warning_specific_message: Remove this unnecessary cast to "int".
warning_start_line: 30
