warning_ID: 747
warning_file_name: BetaCheckerTest.java
warning_file_path: src/test/java/com/google/common/annotations/checkers/BetaCheckerTest.java
warning_repository_URL: https://github.com/google/guava-beta-checker.git
warning_repository_commit: c322cd464a35f3ad44fc0158253bf17808c1ce8c
warning_repository_name: guava-beta-checker
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 646
