warning_ID: 762
warning_file_name: DraftsApiRestClientTest.java
warning_file_path: src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
warning_repository_URL: https://github.com/uwolfer/gerrit-rest-java-client.git
warning_repository_commit: de49b4e19572334d60f381955b72e1aa8bbbab49
warning_repository_name: gerrit-rest-java-client
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "ec047590bc7fb8db7ae03ebac336488bfc1c5e12"
  4 times.
warning_start_line: 39
