warning_ID: 763
warning_file_name: ResourceUtils.java
warning_file_path: src/test/java/si/mazi/rescu/ResourceUtils.java
warning_repository_URL: https://github.com/mmazi/rescu.git
warning_repository_commit: 963e5c2c00ad4a521e0b1876e2aade2cf84866f8
warning_repository_name: rescu
warning_repository_target_java_version: '8'
warning_rule_key: S2093
warning_rule_name: Try-with-resources should be used
warning_rule_type: Code_Smell
warning_specific_message: Change this "try" to a try-with-resources.
warning_start_line: 43
