warning_ID: 767
warning_file_name: HMap.java
warning_file_path: src/main/java/com/jnape/palatable/lambda/adt/hmap/HMap.java
warning_repository_URL: https://github.com/palatable/lambda.git
warning_repository_commit: 3f23529573f7a2f7f7a11aca3d9d7e720cf2a15b
warning_repository_name: lambda
warning_repository_target_java_version: '8'
warning_rule_key: S107
warning_rule_name: Methods should not have too many parameters
warning_rule_type: Code_Smell
warning_specific_message: Method has 16 parameters, which is greater than 7 authorized.
warning_start_line: 416
