warning_ID: 809
warning_file_name: JSON1Test.java
warning_file_path: src/test/java/org/sqlite/JSON1Test.java
warning_repository_URL: https://github.com/xerial/sqlite-jdbc.git
warning_repository_commit: 6ca62fd07bf7faf58e923ba8651757621ffc693c
warning_repository_name: sqlite-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S2095
warning_rule_name: Resources should be closed
warning_rule_type: Bug
warning_specific_message: Use try-with-resources or close this "Statement" in a "finally"
  clause.
warning_start_line: 477
