warning_ID: 818
warning_file_name: PESA2BuilderTest.java
warning_file_path: jmetal-algorithm/src/test/java/org/uma/jmetal/algorithm/multiobjective/pesa2/PESA2BuilderTest.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S1450
warning_rule_name: Private fields only used as local variables in methods should become
  local variables
warning_rule_type: Code_Smell
warning_specific_message: Remove the "mutation" field and declare it as a local variable
  in the relevant methods.
warning_start_line: 30
