warning_ID: 820
warning_file_name: ShortViewLogger.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/services/shortview/ShortViewLogger.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1118
warning_rule_name: Utility classes should not have public constructors
warning_rule_type: Code_Smell
warning_specific_message: Add a private constructor to hide the implicit public one.
warning_start_line: 16
