warning_ID: 834
warning_file_name: Example.java
warning_file_path: examples/src/main/java/examples/Example.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S1144
warning_rule_name: Unused "private" methods should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused private "display" method.
warning_start_line: 269
