warning_ID: 849
warning_file_name: GrammarReader.java
warning_file_path: src/main/java/org/apache/joshua/decoder/ff/tm/GrammarReader.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S3776
warning_rule_name: Cognitive Complexity of methods should not be too high
warning_rule_type: Code_Smell
warning_specific_message: Refactor this method to reduce its Cognitive Complexity
  from 18 to the 15 allowed.
warning_start_line: 122
