warning_ID: 169
warning_file_name: XMLRPCClient.java
warning_file_path: src/main/java/de/timroes/axmlrpc/XMLRPCClient.java
warning_repository_URL: https://github.com/gturri/aXMLRPC.git
warning_repository_commit: 1532363c6d3a06174a88d395b93df58811de5445
warning_repository_name: aXMLRPC
warning_repository_target_java_version: '7'
warning_rule_key: S5527
warning_rule_name: Server hostnames should be verified during SSL/TLS connections
warning_rule_type: Vulnerability
warning_specific_message: Enable server hostname verification on this SSL/TLS connection.
warning_start_line: 787
