warning_ID: 170
warning_file_name: TestUtils.java
warning_file_path: src/test/java/org/kamranzafar/jtar/TestUtils.java
warning_repository_URL: https://github.com/kamranzafar/jtar.git
warning_repository_commit: 4b669cffd740b821c666f3e27d54c6a19d50be3f
warning_repository_name: jtar
warning_repository_target_java_version: '7'
warning_rule_key: S1130
warning_rule_name: '"throws" declarations should not be superfluous'
warning_rule_type: Code_Smell
warning_specific_message: Remove the declaration of thrown exception 'java.io.UnsupportedEncodingException'
  which is a subclass of 'java.io.IOException'.
warning_start_line: 25
