warning_ID: 171
warning_file_name: MongoRule.java
warning_file_path: src/test/java/com/github/vincentrussell/query/mongodb/sql/converter/rule/MongoRule.java
warning_repository_URL: https://github.com/vincentrussell/sql-to-mongo-db-query-converter.git
warning_repository_commit: 961f5c04ef387ee88086908ebacdfb6ef6e3081a
warning_repository_name: sql-to-mongo-db-query-converter
warning_repository_target_java_version: '7'
warning_rule_key: S2119
warning_rule_name: '"Random" objects should be reused'
warning_rule_type: Bug
warning_specific_message: Save and re-use this "Random".
warning_start_line: 57
