warning_ID: 173
warning_file_name: PagedSearchController.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/search/controller/PagedSearchController.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1640
warning_rule_name: Maps with keys that are enum values should be replaced with EnumMap
warning_rule_type: Code_Smell
warning_specific_message: Convert this Map to an EnumMap.
warning_start_line: 696
