warning_ID: 174
warning_file_name: PaintRoadMapping.java
warning_file_path: viewer/src/main/java/org/movsim/viewer/roadmapping/PaintRoadMapping.java
warning_repository_URL: https://github.com/movsim/movsim.git
warning_repository_commit: 24d4f4b83a7d2e14f16419fbf7ce05cb019c8066
warning_repository_name: movsim
warning_repository_target_java_version: '8'
warning_rule_key: S4274
warning_rule_name: Asserts should not be used to check the parameters of a public
  method
warning_rule_type: Code_Smell
warning_specific_message: Replace this assert with a proper check.
warning_start_line: 63
