warning_ID: 179
warning_file_name: SensitiveBsTest.java
warning_file_path: sensitive-test/src/test/java/com/github/houbb/sensitive/test/bs/SensitiveBsTest.java
warning_repository_URL: https://github.com/houbb/sensitive.git
warning_repository_commit: f22bec97d00a10352011bca71efe76b8142a0228
warning_repository_name: sensitive
warning_repository_target_java_version: '7'
warning_rule_key: S2068
warning_rule_name: Hard-coded passwords are security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: '''password'' detected in this expression, review this potentially
  hard-coded password.'
warning_start_line: 31
