warning_ID: 180
warning_file_name: PrecisionModel.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/geom/PrecisionModel.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S2062
warning_rule_name: '"readResolve" methods should be inheritable'
warning_rule_type: Code_Smell
warning_specific_message: Make this class "private" or elevate the visibility of "readResolve".
warning_start_line: 108
