warning_ID: 183
warning_file_name: RDFUploadController.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/jena/RDFUploadController.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S3626
warning_rule_name: Jump statements should not be redundant
warning_rule_type: Code_Smell
warning_specific_message: Remove this redundant jump.
warning_start_line: 164
