warning_ID: 184
warning_file_name: TestUtil.java
warning_file_path: src/test/java/io/opentracing/contrib/jdbc/TestUtil.java
warning_repository_URL: https://github.com/opentracing-contrib/java-jdbc.git
warning_repository_commit: b5cb21418cc77795c6ccdd4a55753c6cb4bc8647
warning_repository_name: java-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S5361
warning_rule_name: '"String#replace" should be preferred to "String#replaceAll"'
warning_rule_type: Code_Smell
warning_specific_message: Replace this call to "replaceAll()" by a call to the "replace()"
  method.
warning_start_line: 50
