warning_ID: 190
warning_file_name: ObjectSchemaTest.java
warning_file_path: protostuff-runtime/src/test/java/io/protostuff/runtime/ObjectSchemaTest.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S2175
warning_rule_name: Inappropriate "Collection" calls should not be made
warning_rule_type: Bug
warning_specific_message: A "Map<HasName, >" cannot contain a "String" in a "HasName"
  type.
warning_start_line: 280
