warning_ID: 194
warning_file_name: JWTInterceptTabController.java
warning_file_path: src/app/controllers/JWTInterceptTabController.java
warning_repository_URL: https://github.com/ozzi-/JWT4B.git
warning_repository_commit: c1e61531a6f4854eda7b9d8a324c10fc861380db
warning_repository_name: JWT4B
warning_repository_target_java_version: '8'
warning_rule_key: S2116
warning_rule_name: '"hashCode" and "toString" should not be called on array instances'
warning_rule_type: Bug
warning_specific_message: Use "Arrays.toString(array)" instead.
warning_start_line: 236
