warning_ID: 195
warning_file_name: DataPacket.java
warning_file_path: src/main/java/cn/nukkit/network/protocol/DataPacket.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S2225
warning_rule_name: '"toString()" and "clone()" methods should not return null'
warning_rule_type: Bug
warning_specific_message: Return a non null object.
warning_start_line: 53
