warning_ID: 299
warning_file_name: BytesTest.java
warning_file_path: src/test/java/com/github/davidmoten/rx2/BytesTest.java
warning_repository_URL: https://github.com/davidmoten/rxjava2-extras.git
warning_repository_commit: 0d8e7e5cad69fcb6b9667e48e2cb2d0c90b80813
warning_repository_name: rxjava2-extras
warning_repository_target_java_version: '6'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "document2.txt"
  4 times.
warning_start_line: 42
