warning_ID: 309
warning_file_name: AbstractStringTest.java
warning_file_path: src/test/java/co/nstant/in/cbor/model/AbstractStringTest.java
warning_repository_URL: https://github.com/c-rack/cbor-java.git
warning_repository_commit: 91798fa96a63937f6eb64473efe10e51a8d9b996
warning_repository_name: cbor-java
warning_repository_target_java_version: '7'
warning_rule_key: S5993
warning_rule_name: Constructors of an "abstract" class should not be declared "public"
warning_rule_type: Code_Smell
warning_specific_message: Change the visibility of this constructor to "protected".
warning_start_line: 21
