warning_ID: 310
warning_file_name: TopicDao.java
warning_file_path: src/main/java/ru/org/linux/topic/TopicDao.java
warning_repository_URL: https://github.com/maxcom/lorsource.git
warning_repository_commit: d195bea72c60acd4a0f4ec48a7374ca4ea6c47d8
warning_repository_name: lorsource
warning_repository_target_java_version: '8'
warning_rule_key: S115
warning_rule_name: Constant names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this constant name to match the regular expression
  '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
warning_start_line: 101
