warning_ID: 313
warning_file_name: RuntimeSettings.java
warning_file_path: aesh/src/main/java/org/aesh/command/settings/RuntimeSettings.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S1066
warning_rule_name: Collapsible "if" statements should be merged
warning_rule_type: Code_Smell
warning_specific_message: Merge this if statement with the enclosing one.
warning_start_line: 66
