warning_ID: 314
warning_file_name: ST_Y.java
warning_file_path: hive/src/main/java/com/esri/hadoop/hive/ST_Y.java
warning_repository_URL: https://github.com/Esri/spatial-framework-for-hadoop.git
warning_repository_commit: 28cc6ab472711da6c2124ad22bd33caa8a78c77c
warning_repository_name: spatial-framework-for-hadoop
warning_repository_target_java_version: '6'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 20
