warning_ID: 334
warning_file_name: JSONBodyTypeAdapterTest.java
warning_file_path: src/test/java/smartrics/rest/fitnesse/fixture/support/JSONBodyTypeAdapterTest.java
warning_repository_URL: https://github.com/smartrics/RestFixture.git
warning_repository_commit: d73c8ccd8dc6a3bae1b652df0874007109888fd9
warning_repository_name: RestFixture
warning_repository_target_java_version: '7'
warning_rule_key: S115
warning_rule_name: Constant names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this constant name to match the regular expression
  '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
warning_start_line: 43
