warning_ID: 337
warning_file_name: TrieTest.java
warning_file_path: src/test/java/org/ahocorasick/trie/TrieTest.java
warning_repository_URL: https://github.com/robert-bor/aho-corasick.git
warning_repository_commit: 012ad8019776e5bae32f1ed22b020c9805cba1f0
warning_repository_name: aho-corasick
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 144
