warning_ID: 339
warning_file_name: PropertiesValidator.java
warning_file_path: src/main/java/com/networknt/schema/PropertiesValidator.java
warning_repository_URL: https://github.com/networknt/json-schema-validator.git
warning_repository_commit: 6cb431f82b41530c35c14f4430e11f3051d82d73
warning_repository_name: json-schema-validator
warning_repository_target_java_version: '8'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 107
