warning_ID: 394
warning_file_name: EpubHTML5StructureCheck.java
warning_file_path: src/main/java/com/adobe/epubcheck/ctc/EpubHTML5StructureCheck.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S1197
warning_rule_name: Array designators "[]" should be on the type, not the variable
warning_rule_type: Code_Smell
warning_specific_message: Move the array designators [] to the type.
warning_start_line: 89
