warning_ID: 701
warning_file_name: LaTeXParserTest.java
warning_file_path: redpen-core/src/test/java/cc/redpen/LaTeXParserTest.java
warning_repository_URL: https://github.com/redpen-cc/redpen.git
warning_repository_commit: cce87e790828cb88dd5c3bfbdcb117d351eb6bbd
warning_repository_name: redpen
warning_repository_target_java_version: '8'
warning_rule_key: S2259
warning_rule_name: Null pointers should not be dereferenced
warning_rule_type: Bug
warning_specific_message: A "NullPointerException" could be thrown; "doc" is nullable
  here.
warning_start_line: 351
