warning_ID: 703
warning_file_name: IPv6AddressTest.java
warning_file_path: src/test/java/io/mola/galimatias/IPv6AddressTest.java
warning_repository_URL: https://github.com/smola/galimatias.git
warning_repository_commit: 0771a10ef5021181fc172b95ac39e9f4c7ada2e8
warning_repository_name: galimatias
warning_repository_target_java_version: '6'
warning_rule_key: S1313
warning_rule_name: Using hardcoded IP addresses is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure using this hardcoded IP address is safe here.
warning_start_line: 51
