warning_ID: 713
warning_file_name: UnixSshFileSystemWatchServiceTest.java
warning_file_path: src/test/java/com/pastdev/jsch/nio/file/UnixSshFileSystemWatchServiceTest.java
warning_repository_URL: https://github.com/lucastheisen/jsch-nio.git
warning_repository_commit: 09a87eb6641eebeb62821018291b97517dc92889
warning_repository_name: jsch-nio
warning_repository_target_java_version: '7'
warning_rule_key: S2259
warning_rule_name: Null pointers should not be dereferenced
warning_rule_type: Bug
warning_specific_message: A "NullPointerException" could be thrown; "took" is nullable
  here.
warning_start_line: 96
