warning_ID: 715
warning_file_name: AccessRequest.java
warning_file_path: src/main/java/org/tinyradius/packet/AccessRequest.java
warning_repository_URL: https://github.com/ctran/TinyRadius.git
warning_repository_commit: 912f8077822c867903be0f10d1b0dc37546ac6ec
warning_repository_name: TinyRadius
warning_repository_target_java_version: '8'
warning_rule_key: S1117
warning_rule_name: Local variables should not shadow class fields
warning_rule_type: Code_Smell
warning_specific_message: Rename "chapChallenge" which hides the field declared at
  line 435.
warning_start_line: 178
