warning_ID: 723
warning_file_name: JsonInput.java
warning_file_path: protostuff-json/src/main/java/io/protostuff/JsonInput.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S3626
warning_rule_name: Jump statements should not be redundant
warning_rule_type: Code_Smell
warning_specific_message: Remove this redundant jump.
warning_start_line: 116
