warning_ID: 724
warning_file_name: GeoHashTest.java
warning_file_path: src/test/java/ch/hsr/geohash/GeoHashTest.java
warning_repository_URL: https://github.com/kungfoo/geohash-java.git
warning_repository_commit: 57f317c6c780ddfd0c9adae3a9403eb399d44a91
warning_repository_name: geohash-java
warning_repository_target_java_version: '7'
warning_rule_key: S3776
warning_rule_name: Cognitive Complexity of methods should not be too high
warning_rule_type: Code_Smell
warning_specific_message: Refactor this method to reduce its Cognitive Complexity
  from 22 to the 15 allowed.
warning_start_line: 472
