warning_ID: 729
warning_file_name: ElevationModule.java
warning_file_path: src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1197
warning_rule_name: Array designators "[]" should be on the type, not the variable
warning_rule_type: Code_Smell
warning_specific_message: Move the array designators [] to the type.
warning_start_line: 575
