warning_ID: 733
warning_file_name: MultiStatusResponseHandlerTest.java
warning_file_path: src/test/java/com/github/sardine/impl/handler/MultiStatusResponseHandlerTest.java
warning_repository_URL: https://github.com/lookfirst/sardine.git
warning_repository_commit: df3d477ecb57529a0741647e8132ab6fcb2f7700
warning_repository_name: sardine
warning_repository_target_java_version: '7'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "<?xml
  version=\"1.0\" encoding=\"UTF-8\"?>" 3 times.
warning_start_line: 70
