warning_ID: 734
warning_file_name: RefactorRetryController.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/edit/RefactorRetryController.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "modeStr"
  3 times.
warning_start_line: 31
