warning_ID: 741
warning_file_name: AbstractListPage.java
warning_file_path: miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S1118
warning_rule_name: Utility classes should not have public constructors
warning_rule_type: Code_Smell
warning_specific_message: Add a private constructor to hide the implicit public one.
warning_start_line: 159
