warning_ID: 890
warning_file_name: SingerTestHelper.java
warning_file_path: singer/src/test/java/com/pinterest/singer/utils/SingerTestHelper.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S4507
warning_rule_name: Delivering code in production with debug features activated is
  security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure this debug feature is deactivated before delivering
  the code in production.
warning_start_line: 76
