warning_ID: 891
warning_file_name: Either.java
warning_file_path: src/main/java/com/purbon/kafka/topology/utils/Either.java
warning_repository_URL: https://github.com/kafka-ops/kafka-topology-builder.git
warning_repository_commit: 451435a5e553457f9bbacb9929ba66210f0f7396
warning_repository_name: kafka-topology-builder
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 15
