warning_ID: 894
warning_file_name: VectorTilesResource.java
warning_file_path: src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1117
warning_rule_name: Local variables should not shadow class fields
warning_rule_type: Code_Smell
warning_specific_message: Rename "layers" which hides the field declared at line 41.
warning_start_line: 77
