warning_ID: 911
warning_file_name: Shapefile.java
warning_file_path: modules/app/src/main/java/org/locationtech/jtstest/testbuilder/io/shapefile/Shapefile.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 118
