warning_ID: 929
warning_file_name: UserBlueprint.java
warning_file_path: core/src/test/java/com/tobedevoured/modelcitizen/blueprint/UserBlueprint.java
warning_repository_URL: https://github.com/mguymon/model-citizen.git
warning_repository_commit: 5d7f40e08de506f489852c4e5cbcd181ee47f704
warning_repository_name: model-citizen
warning_repository_target_java_version: '6'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "email"
  3 times.
warning_start_line: 49
