warning_ID: 944
warning_file_name: Stats.java
warning_file_path: src/main/java/com/garbagemule/MobArena/leaderboards/Stats.java
warning_repository_URL: https://github.com/garbagemule/MobArena.git
warning_repository_commit: 9bc23c61a029e592e8a182368c5d04f4b7d65397
warning_repository_name: MobArena
warning_repository_target_java_version: '8'
warning_rule_key: S1659
warning_rule_name: Multiple variables should not be declared on the same line
warning_rule_type: Code_Smell
warning_specific_message: Declare "shortName" on a separate line.
warning_start_line: 14
