warning_ID: 947
warning_file_name: FlowableRepeatingTransform.java
warning_file_path: src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableRepeatingTransform.java
warning_repository_URL: https://github.com/davidmoten/rxjava2-extras.git
warning_repository_commit: 0d8e7e5cad69fcb6b9667e48e2cb2d0c90b80813
warning_repository_name: rxjava2-extras
warning_repository_target_java_version: '6'
warning_rule_key: S1764
warning_rule_name: Identical expressions should not be used on both sides of a binary
  operator
warning_rule_type: Bug
warning_specific_message: Correct one of the identical sub-expressions on both sides
  of operator "&&"
warning_start_line: 203
