warning_ID: 949
warning_file_name: SMPSORPChangingTheReferencePointsAndChartsRunner.java
warning_file_path: jmetal-example/src/main/java/org/uma/jmetal/example/multiobjective/smpsorp/SMPSORPChangingTheReferencePointsAndChartsRunner.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 128
