warning_ID: 11
warning_file_name: Categories.java
warning_file_path: src/main/java/org/junit/experimental/categories/Categories.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1123
warning_rule_name: Deprecated elements should have both the annotation and the Javadoc
  tag
warning_rule_type: Code_Smell
warning_specific_message: Add the missing @deprecated Javadoc tag.
warning_start_line: 151
