warning_ID: 12
warning_file_name: SystemExitTest.java
warning_file_path: src/test/java/org/junit/tests/running/core/SystemExitTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1124
warning_rule_name: Modifiers should be declared in the correct order
warning_rule_type: Code_Smell
warning_specific_message: Reorder the modifiers to comply with the Java Language Specification.
warning_start_line: 15
