warning_ID: 13
warning_file_name: ClassLevelMethodsWithIgnoredTestsTest.java
warning_file_path: src/test/java/org/junit/tests/running/classes/ClassLevelMethodsWithIgnoredTestsTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1125
warning_rule_name: Boolean literals should not be redundant
warning_rule_type: Code_Smell
warning_specific_message: Remove the unnecessary boolean literal.
warning_start_line: 153
