warning_ID: 14
warning_file_name: Assert.java
warning_file_path: src/main/java/org/junit/Assert.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1126
warning_rule_name: Return of boolean expressions should not be wrapped into an "if-then-else"
  statement
warning_rule_type: Code_Smell
warning_specific_message: Replace this if-then-else statement by a single return statement.
warning_start_line: 618
