warning_ID: 15
warning_file_name: JUnitCoreReturnsCorrectExitCodeTest.java
warning_file_path: src/test/java/org/junit/tests/running/core/JUnitCoreReturnsCorrectExitCodeTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1130
warning_rule_name: '"throws" declarations should not be superfluous'
warning_rule_type: Code_Smell
warning_specific_message: Remove the declaration of thrown exception 'java.lang.Exception',
  as it cannot be thrown from method's body.
warning_start_line: 35
