warning_ID: 20
warning_file_name: ProxyServlet.java
warning_file_path: src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
warning_repository_URL: https://github.com/mitre/HTTP-Proxy-Servlet.git
warning_repository_commit: 34edf588ad9a02fecffe5efbad0d42ec592838ae
warning_repository_name: HTTP-Proxy-Servlet
warning_rule_key: S1149
warning_rule_name: Synchronized classes Vector, Hashtable, Stack and StringBuffer
  should not be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the synchronized class "StringBuffer" by an unsynchronized
  one such as "StringBuilder".
warning_start_line: 765
