warning_ID: 7
warning_file_name: FloatAssertTest.java
warning_file_path: src/test/java/junit/tests/framework/FloatAssertTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S108
warning_rule_name: Nested blocks of code should not be left empty
warning_rule_type: Code_Smell
warning_specific_message: Either remove or fill this block of code.
warning_start_line: 23
