warning_ID: 102
warning_file_name: PROCore.java
warning_file_path: src/main/java/org/apache/joshua/pro/PROCore.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S2677
warning_rule_name: '"read" and "readLine" return values should be used'
warning_rule_type: Bug
warning_specific_message: Use or store the value returned from "readLine" instead
  of throwing it away.
warning_start_line: 1135
