warning_ID: 105
warning_file_name: RuntimeReflectionFieldFactory.java
warning_file_path: protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeReflectionFieldFactory.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S3011
warning_rule_name: Reflection should not be used to increase accessibility of classes,
  methods, or fields
warning_rule_type: Code_Smell
warning_specific_message: This accessibility bypass should be removed.
warning_start_line: 1534
