warning_ID: 107
warning_file_name: IndexController.java
warning_file_path: miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/IndexController.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S1602
warning_rule_name: Lambdas containing only one statement should not nest this statement
  in a block
warning_rule_type: Code_Smell
warning_specific_message: Remove useless curly braces around statement
warning_start_line: 68
