warning_ID: 109
warning_file_name: RoutingContext.java
warning_file_path: src/main/java/org/opentripplanner/routing/core/RoutingContext.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S2157
warning_rule_name: '"Cloneables" should implement "clone"'
warning_rule_type: Code_Smell
warning_specific_message: Add a "clone()" method to this class.
warning_start_line: 42
