warning_ID: 110
warning_file_name: DataPropertyDaoJena.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/dao/jena/DataPropertyDaoJena.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S3981
warning_rule_name: Collection sizes and array length comparisons should make sense
warning_rule_type: Bug
warning_specific_message: The size of "allDataprops" is always ">=0", so update this
  test to use isEmpty().
warning_start_line: 318
