warning_ID: 114
warning_file_name: UntrustedSSL.java
warning_file_path: core/src/main/java/org/openstack4j/core/transport/UntrustedSSL.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S4423
warning_rule_name: Weak SSL/TLS protocols should not be used
warning_rule_type: Vulnerability
warning_specific_message: Change this code to use a stronger protocol.
warning_start_line: 33
