warning_ID: 117
warning_file_name: EnergyArchive.java
warning_file_path: jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/espea/util/EnergyArchive.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S2786
warning_rule_name: Nested "enum"s should not be declared static
warning_rule_type: Code_Smell
warning_specific_message: Remove this redundant "static" qualifier; nested enum types
  are implicitly static.
warning_start_line: 37
