warning_ID: 121
warning_file_name: PointDictController.java
warning_file_path: sds-admin/src/main/java/com/didiglobal/sds/admin/controller/PointDictController.java
warning_repository_URL: https://github.com/didi/sds.git
warning_repository_commit: 46dac33f39bc1720ca108bd61b6375874906ad57
warning_repository_name: sds
warning_repository_target_java_version: '8'
warning_rule_key: S1611
warning_rule_name: Parentheses should be removed from a single lambda input parameter
  when its type is inferred
warning_rule_type: Code_Smell
warning_specific_message: Remove the parentheses around the "pointDictDO" parameter
warning_start_line: 44
