warning_ID: 123
warning_file_name: GrammarPacker.java
warning_file_path: src/main/java/org/apache/joshua/tools/GrammarPacker.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S1210
warning_rule_name: '"equals(Object obj)" should be overridden along with the "compareTo(T
  obj)" method'
warning_rule_type: Code_Smell
warning_specific_message: Override "equals(Object obj)" to comply with the contract
  of the "compareTo(T o)" method.
warning_start_line: 960
