warning_ID: 130
warning_file_name: MemoryDatabase.java
warning_file_path: src/test/java/com/github/jonathanhds/sqlbuilder/support/MemoryDatabase.java
warning_repository_URL: https://github.com/jonathanhds/sql-builder.git
warning_repository_commit: fd2807610fd9f17eb36c8117f93970316631d94b
warning_repository_name: sql-builder
warning_repository_target_java_version: '7'
warning_rule_key: S2115
warning_rule_name: A secure password should be used when connecting to a database
warning_rule_type: Vulnerability
warning_specific_message: Add password protection to this database.
warning_start_line: 20
