warning_ID: 132
warning_file_name: JsonTokener.java
warning_file_path: src/main/java/com/grack/nanojson/JsonTokener.java
warning_repository_URL: https://github.com/mmastrac/nanojson.git
warning_repository_commit: c31d4029fb2f43f5bd4c5dfba5d53f626360af71
warning_repository_name: nanojson
warning_repository_target_java_version: '7'
warning_rule_key: S4719
warning_rule_name: '"StandardCharsets" constants should be preferred'
warning_rule_type: Code_Smell
warning_specific_message: Replace Charset.forName() call with StandardCharsets.UTF_16BE
warning_start_line: 123
