warning_ID: 135
warning_file_name: SmartGetWord.java
warning_file_path: src/main/java/org/nlpcn/commons/lang/tire/SmartGetWord.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S1264
warning_rule_name: A "while" loop should be used instead of a "for" loop
warning_rule_type: Code_Smell
warning_specific_message: Replace this "for" loop with a "while" loop.
warning_start_line: 114
