warning_ID: 139
warning_file_name: AuthenticationManager.java
warning_file_path: src/main/java/de/timroes/axmlrpc/AuthenticationManager.java
warning_repository_URL: https://github.com/gturri/aXMLRPC.git
warning_repository_commit: 1532363c6d3a06174a88d395b93df58811de5445
warning_repository_name: aXMLRPC
warning_repository_target_java_version: '7'
warning_rule_key: S2647
warning_rule_name: Basic authentication should not be used
warning_rule_type: Vulnerability
warning_specific_message: Use a more secure method than basic authentication.
warning_start_line: 51
