warning_ID: 142
warning_file_name: DesignateV2Builders.java
warning_file_path: core/src/main/java/org/openstack4j/openstack/dns/v2/builder/DesignateV2Builders.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S1223
warning_rule_name: Non-constructor methods should not have the same name as the enclosing
  class
warning_rule_type: Code_Smell
warning_specific_message: Rename this method to prevent any misunderstanding or make
  it a constructor.
warning_start_line: 14
