warning_ID: 145
warning_file_name: StreamParser.java
warning_file_path: redpen-core/src/main/java/cc/redpen/parser/latex/StreamParser.java
warning_repository_URL: https://github.com/redpen-cc/redpen.git
warning_repository_commit: cce87e790828cb88dd5c3bfbdcb117d351eb6bbd
warning_repository_name: redpen
warning_repository_target_java_version: '8'
warning_rule_key: S5998
warning_rule_name: Regular expressions should not overflow the stack
warning_rule_type: Bug
warning_specific_message: Refactor this repetition that can lead to a stack overflow
  for large inputs.
warning_start_line: 295
