warning_ID: 150
warning_file_name: BaseGeometryFunction.java
warning_file_path: modules/tests/src/main/java/org/locationtech/jtstest/geomop/BaseGeometryFunction.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S1656
warning_rule_name: Variables should not be self-assigned
warning_rule_type: Bug
warning_specific_message: Remove or correct this useless self-assignment.
warning_start_line: 50
