warning_ID: 153
warning_file_name: BuildHelperMojoTest.java
warning_file_path: build-helper-mojo/src/test/java/com/oracle/wls/buildhelper/BuildHelperMojoTest.java
warning_repository_URL: https://github.com/oracle/weblogic-monitoring-exporter.git
warning_repository_commit: 9d17454fd9e34f05acbf942418c3a92ef40fdec1
warning_repository_name: weblogic-monitoring-exporter
warning_repository_target_java_version: '8'
warning_rule_key: S1075
warning_rule_name: URIs should not be hardcoded
warning_rule_type: Code_Smell
warning_specific_message: Refactor your code to get this URI from a customizable parameter.
warning_start_line: 110
