warning_ID: 158
warning_file_name: Stack.java
warning_file_path: src/main/java/org/apache/joshua/decoder/phrase/Stack.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S3346
warning_rule_name: Expressions used in "assert" should not produce side effects
warning_rule_type: Bug
warning_specific_message: Move this "assert" side effect to another statement.
warning_start_line: 99
