warning_ID: 162
warning_file_name: SVGSalamanderReplacedElementFactory.java
warning_file_path: obsolete-archive/examples/nomaven/svg/src/java/org/xhtmlrenderer/demo/svg/SVGSalamanderReplacedElementFactory.java
warning_repository_URL: https://github.com/danfickle/openhtmltopdf.git
warning_repository_commit: 0dcb7e4b8c80d0fbf6d21f970ccab7a701221b5d
warning_repository_name: openhtmltopdf
warning_repository_target_java_version: '8'
warning_rule_key: S2130
warning_rule_name: Parsing should be used to convert "Strings" to primitives
warning_rule_type: Code_Smell
warning_specific_message: Use "Integer.parseInt" for this string-to-int conversion.
warning_start_line: 86
