warning_ID: 163
warning_file_name: NFAutorizador400.java
warning_file_path: src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java
warning_repository_URL: https://github.com/wmixvideo/nfe.git
warning_repository_commit: d0b2ce5ea0749448b1b3dbb9bef88d7eccd05240
warning_repository_name: nfe
warning_repository_target_java_version: '8'
warning_rule_key: S3923
warning_rule_name: All branches in a conditional structure should not have exactly
  the same implementation
warning_rule_type: Bug
warning_specific_message: This conditional operation returns the same value whether
  the condition is "true" or "false".
warning_start_line: 72
