warning_ID: 73
warning_file_name: AbstractEncoder.java
warning_file_path: src/main/java/co/nstant/in/cbor/encoder/AbstractEncoder.java
warning_repository_URL: https://github.com/c-rack/cbor-java.git
warning_repository_commit: 91798fa96a63937f6eb64473efe10e51a8d9b996
warning_repository_name: cbor-java
warning_repository_target_java_version: '7'
warning_rule_key: S2200
warning_rule_name: '"compareTo" results should not be checked for specific values'
warning_rule_type: Bug
warning_specific_message: Only the sign of the result should be examined.
warning_start_line: 61
