warning_ID: 82
warning_file_name: ChangeApiRestClient.java
warning_file_path: src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
warning_repository_URL: https://github.com/uwolfer/gerrit-rest-java-client.git
warning_repository_commit: de49b4e19572334d60f381955b72e1aa8bbbab49
warning_repository_name: gerrit-rest-java-client
warning_repository_target_java_version: '8'
warning_rule_key: S1144
warning_rule_name: Unused "private" methods should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused private "suggestReviewers" method.
warning_start_line: 261
