warning_ID: 83
warning_file_name: AuditEventKafkaSender.java
warning_file_path: singer-commons/src/main/java/com/pinterest/singer/loggingaudit/client/AuditEventKafkaSender.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S2276
warning_rule_name: '"wait(...)" should be used instead of "Thread.sleep(...)" when
  a lock is held'
warning_rule_type: Bug
warning_specific_message: Replace the call to "Thread.sleep(...)" with a call to "wait(...)".
warning_start_line: 412
