warning_ID: 85
warning_file_name: Requirement.java
warning_file_path: src/main/java/com/vdurmont/semver4j/Requirement.java
warning_repository_URL: https://github.com/vdurmont/semver4j.git
warning_repository_commit: 7653e418d610ffcd2811bcb55fd72d00d420950b
warning_repository_name: semver4j
warning_repository_target_java_version: '7'
warning_rule_key: S5852
warning_rule_name: Using slow regular expressions is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure the regex used here, which is vulnerable to polynomial
  runtime due to backtracking, cannot lead to denial of service.
warning_start_line: 25
