warning_ID: 86
warning_file_name: TimeoutInputStream.java
warning_file_path: src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/TimeoutInputStream.java
warning_repository_URL: https://github.com/vincentrussell/sql-to-mongo-db-query-converter.git
warning_repository_commit: 961f5c04ef387ee88086908ebacdfb6ef6e3081a
warning_repository_name: sql-to-mongo-db-query-converter
warning_repository_target_java_version: '7'
warning_rule_key: S4929
warning_rule_name: '"read(byte[],int,int)" should be overridden'
warning_rule_type: Code_Smell
warning_specific_message: Provide an override of "read(byte[],int,int)" for this class.
warning_start_line: 17
