warning_ID: 87
warning_file_name: GoogleAuthenticator.java
warning_file_path: src/main/java/com/warrenstrange/googleauth/GoogleAuthenticator.java
warning_repository_URL: https://github.com/wstrange/GoogleAuth.git
warning_repository_commit: 5cc0970ed6a269468c5552bbe0268c64012fae8b
warning_repository_name: GoogleAuth
warning_repository_target_java_version: '7'
warning_rule_key: S2440
warning_rule_name: Classes with only "static" methods should not be instantiated
warning_rule_type: Code_Smell
warning_specific_message: Remove this instantiation of "Base64".
warning_start_line: 382
