warning_ID: 89
warning_file_name: QueryTest.java
warning_file_path: src/test/java/org/sqlite/QueryTest.java
warning_repository_URL: https://github.com/xerial/sqlite-jdbc.git
warning_repository_commit: 6ca62fd07bf7faf58e923ba8651757621ffc693c
warning_repository_name: sqlite-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S2077
warning_rule_name: Formatting SQL queries is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure using a dynamically formatted SQL query is safe
  here.
warning_start_line: 205
