warning_ID: 91
warning_file_name: LocalityAwarePartitioner.java
warning_file_path: singer/src/main/java/com/pinterest/singer/writer/partitioners/LocalityAwarePartitioner.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S2168
warning_rule_name: Double-checked locking should not be used
warning_rule_type: Bug
warning_specific_message: Remove this dangerous instance of double-checked locking.
warning_start_line: 47
