warning_ID: 93
warning_file_name: IterableThreadLocal.java
warning_file_path: src/main/java/cn/nukkit/utils/IterableThreadLocal.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S1113
warning_rule_name: The Object.finalize() method should not be overridden
warning_rule_type: Code_Smell
warning_specific_message: Do not override the Object.finalize() method.
warning_start_line: 119
