warning_ID: 419
warning_file_name: PrecisMinusSourceBLEU.java
warning_file_path: src/main/java/org/apache/joshua/metrics/PrecisMinusSourceBLEU.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S4719
warning_rule_name: '"StandardCharsets" constants should be preferred'
warning_rule_type: Code_Smell
warning_specific_message: Replace charset name argument with StandardCharsets.UTF_8
warning_start_line: 109
