warning_ID: 423
warning_file_name: PrivateConstructors_dataenum.java
warning_file_path: dataenum-processor/src/test/resources/hide/ctors/PrivateConstructors_dataenum.java
warning_repository_URL: https://github.com/spotify/dataenum.git
warning_repository_commit: 7a91307ef55cf9ba94391a4572c9d68dba2c56d5
warning_repository_name: dataenum
warning_repository_target_java_version: '8'
warning_rule_key: S114
warning_rule_name: Interface names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this interface name to match the regular expression
  '^[A-Z][a-zA-Z0-9]*$'.
warning_start_line: 26
