warning_ID: 429
warning_file_name: EntityIdValueImpl.java
warning_file_path: wdtk-datamodel/src/main/java/org/wikidata/wdtk/datamodel/implementation/EntityIdValueImpl.java
warning_repository_URL: https://github.com/Wikidata/Wikidata-Toolkit.git
warning_repository_commit: 8400cdd50528f0d21eea93bacf5998ba950b30ce
warning_repository_name: Wikidata-Toolkit
warning_repository_target_java_version: '8'
warning_rule_key: S112
warning_rule_name: Generic exceptions should never be thrown
warning_rule_type: Code_Smell
warning_specific_message: Define and throw a dedicated exception instead of using
  a generic one.
warning_start_line: 217
