warning_ID: 460
warning_file_name: VersionRetriever.java
warning_file_path: src/main/java/com/adobe/epubcheck/opf/VersionRetriever.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S108
warning_rule_name: Nested blocks of code should not be left empty
warning_rule_type: Code_Smell
warning_specific_message: Either remove or fill this block of code.
warning_start_line: 75
