warning_ID: 468
warning_file_name: Utils.java
warning_file_path: obfuscator-core/src/main/java/me/superblaubeere27/jobf/utils/Utils.java
warning_repository_URL: https://github.com/superblaubeere27/obfuscator.git
warning_repository_commit: cc4421d7afe7aead7f59435b28aaba5bc69115b3
warning_repository_name: obfuscator
warning_repository_target_java_version: '8'
warning_rule_key: S131
warning_rule_name: '"switch" statements should have "default" clauses'
warning_rule_type: Code_Smell
warning_specific_message: Add a default case to this switch.
warning_start_line: 388
