warning_ID: 479
warning_file_name: JWTInterceptTabController.java
warning_file_path: src/app/controllers/JWTInterceptTabController.java
warning_repository_URL: https://github.com/ozzi-/JWT4B.git
warning_repository_commit: c1e61531a6f4854eda7b9d8a324c10fc861380db
warning_repository_name: JWT4B
warning_repository_target_java_version: '8'
warning_rule_key: S1604
warning_rule_name: Anonymous inner classes containing only one method should become
  lambdas
warning_rule_type: Code_Smell
warning_specific_message: Make this anonymous inner class a lambda
warning_start_line: 357
