warning_ID: 481
warning_file_name: XMLContentDocParser.java
warning_file_path: src/main/java/com/adobe/epubcheck/ctc/xml/XMLContentDocParser.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 54
