warning_ID: 490
warning_file_name: BLEU.java
warning_file_path: src/main/java/org/apache/joshua/decoder/BLEU.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S112
warning_rule_name: Generic exceptions should never be thrown
warning_rule_type: Code_Smell
warning_specific_message: Define and throw a dedicated exception instead of using
  a generic one.
warning_start_line: 385
