warning_ID: 492
warning_file_name: PopulatorRavines.java
warning_file_path: src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorRavines.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S2184
warning_rule_name: Math operands should be cast before assignment
warning_rule_type: Bug
warning_specific_message: Cast one of the operands of this addition operation to a
  "double".
warning_start_line: 55
