warning_ID: 493
warning_file_name: EpubChecker.java
warning_file_path: src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S127
warning_rule_name: '"for" loop stop conditions should be invariant'
warning_rule_type: Code_Smell
warning_specific_message: Refactor the code in order to not assign to this loop counter
  from within the loop body.
warning_start_line: 554
