warning_ID: 495
warning_file_name: PBKDF2FunctionTest.java
warning_file_path: src/test/com/password4j/PBKDF2FunctionTest.java
warning_repository_URL: https://github.com/Password4j/password4j.git
warning_repository_commit: 722f724f5f59e321eb16e9f46c3033cbd5e80ba9
warning_repository_name: password4j
warning_repository_target_java_version: '8'
warning_rule_key: S2068
warning_rule_name: Hard-coded passwords are security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: '''password'' detected in this expression, review this potentially
  hard-coded password.'
warning_start_line: 127
