warning_ID: 496
warning_file_name: RFC3339DateFormat.java
warning_file_path: src/main/java/io/gsonfire/util/RFC3339DateFormat.java
warning_repository_URL: https://github.com/julman99/gson-fire.git
warning_repository_commit: 5dd4cd703065b0d4127390c6bdec1fb434ebec71
warning_repository_name: gson-fire
warning_repository_target_java_version: '6'
warning_rule_key: S6353
warning_rule_name: Regular expression quantifiers and character classes should be
  used concisely
warning_rule_type: Code_Smell
warning_specific_message: Use concise character class syntax '\\d' instead of '[0-9]'.
warning_start_line: 16
