warning_ID: 499
warning_file_name: FileListerTest.java
warning_file_path: aesh/src/test/java/org/aesh/util/FileListerTest.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S112
warning_rule_name: Generic exceptions should never be thrown
warning_rule_type: Code_Smell
warning_specific_message: Define and throw a dedicated exception instead of using
  a generic one.
warning_start_line: 207
