warning_ID: 500
warning_file_name: CssParserTest.java
warning_file_path: src/test/java/org/idpf/epubcheck/util/css/CssParserTest.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S2479
warning_rule_name: Whitespace and control characters in literals should be explicit
warning_rule_type: Code_Smell
warning_specific_message: Remove the non-escaped \u0009 character from this literal.
warning_start_line: 1657
