warning_ID: 502
warning_file_name: TopoGraph.java
warning_file_path: src/main/java/com/esri/core/geometry/TopoGraph.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S135
warning_rule_name: Loops should not contain more than a single "break" or "continue"
  statement
warning_rule_type: Code_Smell
warning_specific_message: Reduce the total number of break and continue statements
  in this loop to use at most one.
warning_start_line: 1369
