warning_ID: 506
warning_file_name: TemporalConverters.java
warning_file_path: src/main/java/org/exparity/hamcrest/date/core/TemporalConverters.java
warning_repository_URL: https://github.com/eXparity/hamcrest-date.git
warning_repository_commit: ff8228204fa9e40c8d6192ea4977035c0d0494e5
warning_repository_name: hamcrest-date
warning_repository_target_java_version: '8'
warning_rule_key: S3008
warning_rule_name: Static non-final field names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this field "LOCALDATETIME_AS_LOCALDATE" to match
  the regular expression '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 119
