warning_ID: 525
warning_file_name: ExternalSort.java
warning_file_path: src/main/java/com/google/code/externalsorting/ExternalSort.java
warning_repository_URL: https://github.com/lemire/externalsortinginjava.git
warning_repository_commit: 418f16c96186e2b8cac255bbb05f6119cfdc8e64
warning_repository_name: externalsortinginjava
warning_repository_target_java_version: '8'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 58
