warning_ID: 534
warning_file_name: ArrayIterator.java
warning_file_path: core/src/main/java/org/modelmapper/internal/util/ArrayIterator.java
warning_repository_URL: https://github.com/modelmapper/modelmapper.git
warning_repository_commit: f6321b01863e44a75d2b2ee52dbaf4f62cfa550b
warning_repository_name: modelmapper
warning_repository_target_java_version: '6'
warning_rule_key: S1161
warning_rule_name: '"@Override" should be used on overriding and implementing methods'
warning_rule_type: Code_Smell
warning_specific_message: Add the "@Override" annotation above this method signature
warning_start_line: 46
