warning_ID: 538
warning_file_name: TestHalfEdges.java
warning_file_path: src/test/java/org/opentripplanner/routing/TestHalfEdges.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1450
warning_rule_name: Private fields only used as local variables in methods should become
  local variables
warning_rule_type: Code_Smell
warning_specific_message: Remove the "tl" field and declare it as a local variable
  in the relevant methods.
warning_start_line: 57
