warning_ID: 548
warning_file_name: Recording.java
warning_file_path: src/main/java/simplenlg/xmlrealiser/Recording.java
warning_repository_URL: https://github.com/simplenlg/simplenlg.git
warning_repository_commit: c65331a528f0241c29051c7a086ae5e9518e07e2
warning_repository_name: simplenlg
warning_repository_target_java_version: '8'
warning_rule_key: S2755
warning_rule_name: XML parsers should not be vulnerable to XXE attacks
warning_rule_type: Vulnerability
warning_specific_message: Disable access to external entities in XML parsing.
warning_start_line: 179
