FROM mcr.microsoft.com/devcontainers/base:jammy
RUN sudo apt-get update && sudo apt-get install -y openjdk-11-jdk libdbi-perl dos2unix bash-builtins maven
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64