warning_ID: 63
warning_file_name: Ride.java
warning_file_path: src/main/java/org/opentripplanner/routing/impl/Ride.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1155
warning_rule_name: Collection.isEmpty() should be used to test for emptiness
warning_rule_type: Code_Smell
warning_specific_message: Use isEmpty() to check whether the collection is empty or
  not.
warning_start_line: 55
