warning_ID: 71
warning_file_name: SaharaConfigInfo.java
warning_file_path: core/src/main/java/org/openstack4j/openstack/sahara/domain/SaharaConfigInfo.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S4275
warning_rule_name: Getters and setters should access the expected fields
warning_rule_type: Bug
warning_specific_message: Refactor this getter so that it actually refers to the field
  "defaultValue".
warning_start_line: 41
