warning_ID: 74
warning_file_name: Migration.java
warning_file_path: migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/Migration.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S4507
warning_rule_name: Delivering code in production with debug features activated is
  security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure this debug feature is deactivated before delivering
  the code in production.
warning_start_line: 54
