warning_ID: 77
warning_file_name: GeometryStrategies.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/io/gml2/GeometryStrategies.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S2153
warning_rule_name: Boxing and unboxing should not be immediately reversed
warning_rule_type: Bug
warning_specific_message: Remove the unboxing from "Double".
warning_start_line: 436
