warning_ID: 78
warning_file_name: KvpByteArrayInput.java
warning_file_path: protostuff-kvp/src/main/java/io/protostuff/KvpByteArrayInput.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S3034
warning_rule_name: Raw byte values should not be used in bitwise operations in combination
  with shifts
warning_rule_type: Bug
warning_specific_message: Prevent "int" promotion by adding "& 0xff" to this expression.
warning_start_line: 103
