warning_ID: 79
warning_file_name: ConfigurationServletTest.java
warning_file_path: wls-exporter-core/src/test/java/com/oracle/wls/exporter/ConfigurationServletTest.java
warning_repository_URL: https://github.com/oracle/weblogic-monitoring-exporter.git
warning_repository_commit: 9d17454fd9e34f05acbf942418c3a92ef40fdec1
warning_repository_name: weblogic-monitoring-exporter
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 113
