warning_ID: 80
warning_file_name: GrammarReader.java
warning_file_path: src/main/java/org/apache/joshua/decoder/ff/tm/GrammarReader.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S4348
warning_rule_name: '"iterator" should not return "this"'
warning_rule_type: Bug
warning_specific_message: Refactor this code so that the Iterator supports multiple
  traversal
warning_start_line: 63
