warning_ID: 81
warning_file_name: ViewerHelper.java
warning_file_path: MSGViewer/src/main/java/net/sourceforge/MSGViewer/ViewerHelper.java
warning_repository_URL: https://github.com/lolo101/MsgViewer.git
warning_repository_commit: 42266b9a62ec9706b1042f118fd6f57c6f074fd2
warning_repository_name: MsgViewer
warning_repository_target_java_version: '11'
warning_rule_key: S2112
warning_rule_name: '"URL.hashCode" and "URL.equals" should be avoided'
warning_rule_type: Code_Smell
warning_specific_message: Use the URI class instead.
warning_start_line: 209
