warning_ID: 84
warning_file_name: NFOperadoraCartao.java
warning_file_path: src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFOperadoraCartao.java
warning_repository_URL: https://github.com/wmixvideo/nfe.git
warning_repository_commit: d0b2ce5ea0749448b1b3dbb9bef88d7eccd05240
warning_repository_name: nfe
warning_repository_target_java_version: '8'
warning_rule_key: S3066
warning_rule_name: '"enum" fields should not be publicly mutable'
warning_rule_type: Code_Smell
warning_specific_message: Lower the visibility of this setter or remove it altogether.
warning_start_line: 50
