warning_ID: 88
warning_file_name: MorphologyRules.java
warning_file_path: src/main/java/simplenlg/morphology/english/MorphologyRules.java
warning_repository_URL: https://github.com/simplenlg/simplenlg.git
warning_repository_commit: c65331a528f0241c29051c7a086ae5e9518e07e2
warning_repository_name: simplenlg
warning_repository_target_java_version: '8'
warning_rule_key: S5869
warning_rule_name: Character classes in regular expressions should not contain the
  same character twice
warning_rule_type: Code_Smell
warning_specific_message: Remove duplicates in this character class.
warning_start_line: 212
