warning_ID: 95
warning_file_name: RoutingResource.java
warning_file_path: src/main/java/org/opentripplanner/api/common/RoutingResource.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S6355
warning_rule_name: Deprecated annotations should include explanations
warning_rule_type: Code_Smell
warning_specific_message: Add 'since' and/or 'forRemoval' arguments to the @Deprecated
  annotation.
warning_start_line: 60
