warning_ID: 99
warning_file_name: SqlServerURLParser.java
warning_file_path: src/main/java/io/opentracing/contrib/jdbc/parser/SqlServerURLParser.java
warning_repository_URL: https://github.com/opentracing-contrib/java-jdbc.git
warning_repository_commit: b5cb21418cc77795c6ccdd4a55753c6cb4bc8647
warning_repository_name: java-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S108
warning_rule_name: Nested blocks of code should not be left empty
warning_rule_type: Code_Smell
warning_specific_message: Either remove or fill this block of code.
warning_start_line: 52
