warning_ID: 952
warning_file_name: ThresholdMixinPerfTest.java
warning_file_path: src/test/java/com/networknt/schema/ThresholdMixinPerfTest.java
warning_repository_URL: https://github.com/networknt/json-schema-validator.git
warning_repository_commit: 6cb431f82b41530c35c14f4430e11f3051d82d73
warning_repository_name: json-schema-validator
warning_repository_target_java_version: '8'
warning_rule_key: S3457
warning_rule_name: Printf-style format strings should be used correctly
warning_rule_type: Code_Smell
warning_specific_message: '%n should be used in place of \n to produce the platform-specific
  line separator.'
warning_start_line: 114
