warning_ID: 962
warning_file_name: TimeEstimate.java
warning_file_path: src/main/java/me/gosimple/nbvcxz/scoring/TimeEstimate.java
warning_repository_URL: https://github.com/GoSimpleLLC/nbvcxz.git
warning_repository_commit: dc1c098a5d1725d94b8c019b3ccadcd9b3869862
warning_repository_name: nbvcxz
warning_repository_target_java_version: '7'
warning_rule_key: S1874
warning_rule_name: '"@Deprecated" code should not be used'
warning_rule_type: Code_Smell
warning_specific_message: Remove this use of "ROUND_FLOOR"; it is deprecated.
warning_start_line: 63
