warning_ID: 964
warning_file_name: GreaterThanOrEqualTest.java
warning_file_path: src/test/java/net/kaczmarzyk/spring/data/jpa/domain/GreaterThanOrEqualTest.java
warning_repository_URL: https://github.com/tkaczmarzyk/specification-arg-resolver.git
warning_repository_commit: 52fe8d284f687ec86fea91b48f47d61dc6b32510
warning_repository_name: specification-arg-resolver
warning_repository_target_java_version: '8'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 35
