warning_ID: 966
warning_file_name: CustomConversion.java
warning_file_path: core/src/test/java/org/modelmapper/functional/converter/CustomConversion.java
warning_repository_URL: https://github.com/modelmapper/modelmapper.git
warning_repository_commit: f6321b01863e44a75d2b2ee52dbaf4f62cfa550b
warning_repository_name: modelmapper
warning_repository_target_java_version: '6'
warning_rule_key: S101
warning_rule_name: Class names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.
warning_start_line: 297
