warning_ID: 967
warning_file_name: BufferCorrectnessTest.java
warning_file_path: modules/core/src/test/java/test/jts/perf/operation/buffer/BufferCorrectnessTest.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S4507
warning_rule_name: Delivering code in production with debug features activated is
  security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure this debug feature is deactivated before delivering
  the code in production.
warning_start_line: 38
