warning_ID: 986
warning_file_name: HWIDProtection.java
warning_file_path: obfuscator-core/src/main/java/me/superblaubeere27/jobf/processors/HWIDProtection.java
warning_repository_URL: https://github.com/superblaubeere27/obfuscator.git
warning_repository_commit: cc4421d7afe7aead7f59435b28aaba5bc69115b3
warning_repository_name: obfuscator
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
  7 times.
warning_start_line: 70
