warning_ID: 21
warning_file_name: AssumptionTest.java
warning_file_path: src/test/java/org/junit/tests/experimental/AssumptionTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S115
warning_rule_name: Constant names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this constant name to match the regular expression
  '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
warning_start_line: 240
