warning_ID: 22
warning_file_name: MethodValidator.java
warning_file_path: src/main/java/org/junit/internal/runners/MethodValidator.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1155
warning_rule_name: Collection.isEmpty() should be used to test for emptiness
warning_rule_type: Code_Smell
warning_specific_message: Use isEmpty() to check whether the collection is empty or
  not.
warning_start_line: 38
