warning_ID: 25
warning_file_name: MessageDialog.java
warning_file_path: src/main/java/jpass/ui/MessageDialog.java
warning_repository_URL: https://github.com/gaborbata/jpass.git
warning_repository_commit: f52b8ae1bf2e1154aa800c784c244d3fbb63c643
warning_repository_name: jpass
warning_rule_key: S1168
warning_rule_name: Empty arrays and collections should be returned instead of null
warning_rule_type: Code_Smell
warning_specific_message: Return an empty array instead of null.
warning_start_line: 277
