warning_ID: 29
warning_file_name: MethodSorterTest.java
warning_file_path: src/test/java/org/junit/internal/MethodSorterTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1186
warning_rule_name: Methods should not be empty
warning_rule_type: Code_Smell
warning_specific_message: Add a nested comment explaining why this method is empty,
  throw an UnsupportedOperationException or complete the implementation.
warning_start_line: 40
