warning_ID: 30
warning_file_name: FrameworkMethod.java
warning_file_path: src/main/java/org/junit/runners/model/FrameworkMethod.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "Method
  " 4 times.
warning_start_line: 85
