warning_ID: 202
warning_file_name: AttributeStreamOfDbl.java
warning_file_path: src/main/java/com/esri/core/geometry/AttributeStreamOfDbl.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S2589
warning_rule_name: Boolean expressions should not be gratuitous
warning_rule_type: Code_Smell
warning_specific_message: Remove this expression which always evaluates to "true"
warning_start_line: 348
