warning_ID: 205
warning_file_name: Fallback.java
warning_file_path: src/main/java/net/jodah/failsafe/Fallback.java
warning_repository_URL: https://github.com/jhalterman/failsafe.git
warning_repository_commit: f9ddba08a7b218c0f14dc8f713709b2e28aeab65
warning_repository_name: failsafe
warning_repository_target_java_version: '8'
warning_rule_key: S1700
warning_rule_name: A field should not duplicate the name of its containing class
warning_rule_type: Code_Smell
warning_specific_message: Rename field "fallback"
warning_start_line: 46
