warning_ID: 209
warning_file_name: WKBWriter.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/io/WKBWriter.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S2681
warning_rule_name: Multiline blocks should be enclosed in curly braces
warning_rule_type: Code_Smell
warning_specific_message: This line will not be executed conditionally; only the first
  line of this 2-line block will be. The rest will execute unconditionally.
warning_start_line: 440
