warning_ID: 210
warning_file_name: GeneralizedSpread.java
warning_file_path: jmetal-experimental/src/main/java/org/uma/jmetal/experimental/qualityIndicator/impl/GeneralizedSpread.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S3012
warning_rule_name: Arrays should not be copied using loops
warning_rule_type: Code_Smell
warning_specific_message: Use "Arrays.copyOf", "Arrays.asList", "Collections.addAll"
  or "System.arraycopy" instead.
warning_start_line: 82
