warning_ID: 211
warning_file_name: DedupAndExtract.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/utils/jena/DedupAndExtract.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S2178
warning_rule_name: Short-circuit logic should be used in boolean contexts
warning_rule_type: Code_Smell
warning_specific_message: Correct this "&" to "&&" and extract the right operand to
  a variable if it should always be evaluated.
warning_start_line: 47
