warning_ID: 218
warning_file_name: AccessSelectorTest.java
warning_file_path: dataenum-processor/src/test/java/com/spotify/dataenum/processor/AccessSelectorTest.java
warning_repository_URL: https://github.com/spotify/dataenum.git
warning_repository_commit: 7a91307ef55cf9ba94391a4572c9d68dba2c56d5
warning_repository_name: dataenum
warning_repository_target_java_version: '8'
warning_rule_key: S3985
warning_rule_name: Unused "private" classes should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused private "FakeElement" class.
warning_start_line: 221
