warning_ID: 220
warning_file_name: SetupCommand.java
warning_file_path: src/main/java/com/garbagemule/MobArena/commands/setup/SetupCommand.java
warning_repository_URL: https://github.com/garbagemule/MobArena.git
warning_repository_commit: 9bc23c61a029e592e8a182368c5d04f4b7d65397
warning_repository_name: MobArena
warning_repository_target_java_version: '8'
warning_rule_key: S1301
warning_rule_name: '"switch" statements should have at least 3 "case" clauses'
warning_rule_type: Code_Smell
warning_specific_message: Replace this "switch" statement by "if" statements to increase
  readability.
warning_start_line: 364
