warning_ID: 224
warning_file_name: WFGHypervolume.java
warning_file_path: jmetal-experimental/src/main/java/org/uma/jmetal/experimental/qualityIndicator/impl/hypervolume/impl/WFGHypervolume.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S5261
warning_rule_name: '"else" statements should be clearly matched with an "if"'
warning_rule_type: Code_Smell
warning_specific_message: Add explicit curly braces to avoid dangling else.
warning_start_line: 421
