warning_ID: 231
warning_file_name: DefaultLogMonitor.java
warning_file_path: singer/src/main/java/com/pinterest/singer/monitor/DefaultLogMonitor.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S1860
warning_rule_name: Synchronization should not be done on instances of value-based
  classes
warning_rule_type: Bug
warning_specific_message: Synchronize on a new "Object" instead.
warning_start_line: 409
