warning_ID: 239
warning_file_name: LevenshteinDistance.java
warning_file_path: redpen-core/src/main/java/cc/redpen/util/LevenshteinDistance.java
warning_repository_URL: https://github.com/redpen-cc/redpen.git
warning_repository_commit: cce87e790828cb88dd5c3bfbdcb117d351eb6bbd
warning_repository_name: redpen
warning_repository_target_java_version: '8'
warning_rule_key: S2886
warning_rule_name: Getters and setters should be synchronized in pairs
warning_rule_type: Bug
warning_specific_message: Synchronize this method to match the synchronization on
  "setInsertionCost".
warning_start_line: 65
