warning_ID: 242
warning_file_name: StackTraceUtility.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/utils/developer/loggers/StackTraceUtility.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S3457
warning_rule_name: Printf-style format strings should be used correctly
warning_rule_type: Code_Smell
warning_specific_message: '%n should be used in place of \n to produce the platform-specific
  line separator.'
warning_start_line: 127
