warning_ID: 243
warning_file_name: RNSGAIIRanking.java
warning_file_path: jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/rnsgaii/util/RNSGAIIRanking.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S5413
warning_rule_name: '''List.remove()'' should not be used in ascending ''for'' loops'
warning_rule_type: Code_Smell
warning_specific_message: Verify that "remove()" is used correctly.
warning_start_line: 105
