warning_ID: 248
warning_file_name: RtSwarm.java
warning_file_path: src/main/java/com/amihaiemil/docker/RtSwarm.java
warning_repository_URL: https://github.com/amihaiemil/docker-java-api.git
warning_repository_commit: 653943a3012fe104ff5d226351cebbe52785eba5
warning_repository_name: docker-java-api
warning_repository_target_java_version: '8'
warning_rule_key: S1153
warning_rule_name: String.valueOf() should not be appended to a String
warning_rule_type: Code_Smell
warning_specific_message: Directly append the argument of String.valueOf().
warning_start_line: 113
