warning_ID: 250
warning_file_name: UrlBuilder.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/UrlBuilder.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S3020
warning_rule_name: '"toArray" should be passed an array of the proper type'
warning_rule_type: Bug
warning_specific_message: Pass "new String[0]" as argument to "toArray".
warning_start_line: 149
