warning_ID: 251
warning_file_name: ArrayIterator.java
warning_file_path: core/src/main/java/org/modelmapper/internal/util/ArrayIterator.java
warning_repository_URL: https://github.com/modelmapper/modelmapper.git
warning_repository_commit: f6321b01863e44a75d2b2ee52dbaf4f62cfa550b
warning_repository_name: modelmapper
warning_repository_target_java_version: '6'
warning_rule_key: S2272
warning_rule_name: '"Iterator.next()" methods should throw "NoSuchElementException"'
warning_rule_type: Bug
warning_specific_message: Add a "NoSuchElementException" for iteration beyond the
  end of the collection.
warning_start_line: 42
