warning_ID: 260
warning_file_name: Fn0Test.java
warning_file_path: src/test/java/com/jnape/palatable/lambda/functions/Fn0Test.java
warning_repository_URL: https://github.com/palatable/lambda.git
warning_repository_commit: 3f23529573f7a2f7f7a11aca3d9d7e720cf2a15b
warning_repository_name: lambda
warning_repository_target_java_version: '8'
warning_rule_key: S4276
warning_rule_name: Functional Interfaces should be as specialised as possible
warning_rule_type: Code_Smell
warning_specific_message: Refactor this code to use the more specialised Functional
  Interface 'IntSupplier'
warning_start_line: 29
