warning_ID: 262
warning_file_name: Stemmer.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vedit/util/Stemmer.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S3973
warning_rule_name: A conditionally executed single line should be denoted by indentation
warning_rule_type: Code_Smell
warning_specific_message: Use indentation to denote the code conditionally executed
  by this "if".
warning_start_line: 246
