warning_ID: 266
warning_file_name: JObf.java
warning_file_path: obfuscator-core/src/main/java/me/superblaubeere27/jobf/JObf.java
warning_repository_URL: https://github.com/superblaubeere27/obfuscator.git
warning_repository_commit: cc4421d7afe7aead7f59435b28aaba5bc69115b3
warning_repository_name: obfuscator
warning_repository_target_java_version: '8'
warning_rule_key: S4792
warning_rule_name: Configuring loggers is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure that this logger's configuration is safe.
warning_start_line: 61
