warning_ID: 268
warning_file_name: XMLRealiserTest.java
warning_file_path: src/test/java/simplenlg/xmlrealiser/XMLRealiserTest.java
warning_repository_URL: https://github.com/simplenlg/simplenlg.git
warning_repository_commit: c65331a528f0241c29051c7a086ae5e9518e07e2
warning_repository_name: simplenlg
warning_repository_target_java_version: '8'
warning_rule_key: S6019
warning_rule_name: Reluctant quantifiers in regular expressions should be followed
  by an expression that can't match the empty string
warning_rule_type: Code_Smell
warning_specific_message: Fix this reluctant quantifier that will only ever match
  2 repetitions.
warning_start_line: 112
