warning_ID: 269
warning_file_name: ContactMailController.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/ContactMailController.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1141
warning_rule_name: Try-catch blocks should not be nested
warning_rule_type: Code_Smell
warning_specific_message: Extract this nested try block into a separate method.
warning_start_line: 125
