warning_ID: 280
warning_file_name: MapWiringTests.java
warning_file_path: src/test/java/org/springframework/guice/MapWiringTests.java
warning_repository_URL: https://github.com/spring-projects/spring-guice.git
warning_repository_commit: ebfdb1be8eabafc55d0007ff2ec194ddc6f6f15c
warning_repository_name: spring-guice
warning_repository_target_java_version: '8'
warning_rule_key: S2094
warning_rule_name: Classes should not be empty
warning_rule_type: Code_Smell
warning_specific_message: Remove this empty class, write its code or make it an "interface".
warning_start_line: 57
