warning_ID: 284
warning_file_name: Base64.java
warning_file_path: MyPerf4J-Base/src/main/java/cn/myperf4j/base/util/Base64.java
warning_repository_URL: https://github.com/LinShunKang/MyPerf4J.git
warning_repository_commit: caed27c4e35d7ba6841024a8a58c5ed33079ddfb
warning_repository_name: MyPerf4J
warning_repository_target_java_version: '7'
warning_rule_key: S127
warning_rule_name: '"for" loop stop conditions should be invariant'
warning_rule_type: Code_Smell
warning_specific_message: Refactor the code in order to not assign to this loop counter
  from within the loop body.
warning_start_line: 133
