warning_ID: 288
warning_file_name: InvokeReceiver.java
warning_file_path: pitest/src/main/java/sun/pitest/InvokeReceiver.java
warning_repository_URL: https://github.com/hcoles/pitest.git
warning_repository_commit: b3d752994e4e0234bb9494e739b1960240f1f9d3
warning_repository_name: pitest
warning_repository_target_java_version: '8'
warning_rule_key: S1191
warning_rule_name: Classes from "sun.*" packages should not be used
warning_rule_type: Code_Smell
warning_specific_message: Use classes from the Java API instead of Sun classes.
warning_start_line: 1
