warning_ID: 290
warning_file_name: ModelUpdate.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/reasoner/ModelUpdate.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S1116
warning_rule_name: Empty statements should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this empty statement.
warning_start_line: 10
