warning_ID: 206
warning_file_name: ModelSerializer.java
warning_file_path: carml-commons/src/main/java/com/taxonic/carml/util/ModelSerializer.java
warning_repository_URL: https://github.com/carml/carml.git
warning_repository_commit: 181d2cbb0364b38168c2f9241280464f41b31c3f
warning_repository_name: carml
warning_repository_target_java_version: '8'
warning_rule_key: S6395
warning_rule_name: Non-capturing groups without quantifier should not be used
warning_rule_type: Code_Smell
warning_specific_message: Unwrap this unnecessarily grouped subpattern.
warning_start_line: 25
