warning_ID: 213
warning_file_name: JenaBaseDao.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/dao/jena/JenaBaseDao.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S2447
warning_rule_name: Null should not be returned from a "Boolean" method
warning_rule_type: Code_Smell
warning_specific_message: Null is returned but a "Boolean" is expected.
warning_start_line: 155
