warning_ID: 214
warning_file_name: BoxScannerTests.java
warning_file_path: integration-tools/src/test/java/uk/ac/bbsrc/tgac/miso/integration/test/BoxScannerTests.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S1217
warning_rule_name: '"Thread.run()" should not be called directly'
warning_rule_type: Bug
warning_specific_message: Call the method Thread.start() to execute the content of
  the run() method in a dedicated thread.
warning_start_line: 73
