warning_ID: 216
warning_file_name: ThriftCodec.java
warning_file_path: thrift-logger/src/main/java/com/pinterest/singer/client/ThriftCodec.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S2209
warning_rule_name: '"static" members should be accessed statically'
warning_rule_type: Code_Smell
warning_specific_message: Change this instance-reference to a static reference.
warning_start_line: 93
