warning_ID: 217
warning_file_name: Result.java
warning_file_path: Scientist4JCore/src/main/java/com/github/rawls238/scientist4j/Result.java
warning_repository_URL: https://github.com/rawls238/Scientist4J.git
warning_repository_commit: 4fb34172a7c6acb2ea2ef107c5fc4ebc52b0c526
warning_repository_name: Scientist4J
warning_repository_target_java_version: '8'
warning_rule_key: S1163
warning_rule_name: Exceptions should not be thrown in finally blocks
warning_rule_type: Code_Smell
warning_specific_message: Refactor this code to not throw exceptions in finally blocks.
warning_start_line: 31
