warning_ID: 223
warning_file_name: UnmodMap.java
warning_file_path: src/main/java/org/organicdesign/fp/collections/UnmodMap.java
warning_repository_URL: https://github.com/GlenKPeterson/Paguro.git
warning_repository_commit: de98375df2dd9c26a8cb618d51862f52c64602af
warning_repository_name: Paguro
warning_repository_target_java_version: '11'
warning_rule_key: S2066
warning_rule_name: '"Serializable" inner classes of non-serializable classes should
  be "static"'
warning_rule_type: Bug
warning_specific_message: Make "keySet" static
warning_start_line: 267
