warning_ID: 235
warning_file_name: SmartForest.java
warning_file_path: src/main/java/org/nlpcn/commons/lang/tire/domain/SmartForest.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S1201
warning_rule_name: '"equals" method overrides should accept "Object" parameters'
warning_rule_type: Bug
warning_specific_message: Either override Object.equals(Object), or rename the method
  to prevent any confusion.
warning_start_line: 148
