warning_ID: 238
warning_file_name: Optimizer.java
warning_file_path: src/main/java/org/apache/joshua/pro/Optimizer.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S1643
warning_rule_name: Strings should not be concatenated using '+' in a loop
warning_rule_type: Code_Smell
warning_specific_message: Use a StringBuilder instead.
warning_start_line: 290
