warning_ID: 241
warning_file_name: RetryPolicyExecutor.java
warning_file_path: src/main/java/net/jodah/failsafe/RetryPolicyExecutor.java
warning_repository_URL: https://github.com/jhalterman/failsafe.git
warning_repository_commit: f9ddba08a7b218c0f14dc8f713709b2e28aeab65
warning_repository_name: failsafe
warning_repository_target_java_version: '8'
warning_rule_key: S3078
warning_rule_name: '"volatile" variables should not be used with compound operators'
warning_rule_type: Bug
warning_specific_message: Use an "AtomicInteger" for this field; its operations are
  atomic.
warning_start_line: 154
