warning_ID: 246
warning_file_name: RestClientDriver.java
warning_file_path: rest-client-driver/src/main/java/com/github/restdriver/clientdriver/RestClientDriver.java
warning_repository_URL: https://github.com/rest-driver/rest-driver.git
warning_repository_commit: b4f3dc9797a757d039b5bdd5563058210808d648
warning_repository_name: rest-driver
warning_repository_target_java_version: '8'
warning_rule_key: S2142
warning_rule_name: '"InterruptedException" should not be ignored'
warning_rule_type: Bug
warning_specific_message: Either re-interrupt this method or rethrow the "InterruptedException"
  that can be caught here.
warning_start_line: 141
