warning_ID: 252
warning_file_name: UserAgentServiceTest.java
warning_file_path: src/test/java/com/blueconic/browscap/impl/UserAgentServiceTest.java
warning_repository_URL: https://github.com/blueconic/browscap-java.git
warning_repository_commit: 049b8cf88a9588fd427cf0d9bdfef8c48fd4f81a
warning_repository_name: browscap-java
warning_repository_target_java_version: '8'
warning_rule_key: S6326
warning_rule_name: Regular expressions should not contain multiple spaces
warning_rule_type: Code_Smell
warning_specific_message: Replace spaces with quantifier `{4}`.
warning_start_line: 135
