warning_ID: 254
warning_file_name: KeystoneAccess.java
warning_file_path: core/src/main/java/org/openstack4j/openstack/identity/v2/domain/KeystoneAccess.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S3064
warning_rule_name: Assignment of lazy-initialized members should be the last step
  with double-checked locking
warning_rule_type: Bug
warning_specific_message: Fully initialize "aggregatedCatalog" before assigning it.
warning_start_line: 68
