warning_ID: 259
warning_file_name: ExternalSort.java
warning_file_path: src/main/java/com/google/code/externalsorting/ExternalSort.java
warning_repository_URL: https://github.com/lemire/externalsortinginjava.git
warning_repository_commit: 418f16c96186e2b8cac255bbb05f6119cfdc8e64
warning_repository_name: externalsortinginjava
warning_repository_target_java_version: '8'
warning_rule_key: S1215
warning_rule_name: Execution of the Garbage Collector should be triggered only by
  the JVM
warning_rule_type: Code_Smell
warning_specific_message: Don't try to be smarter than the JVM, remove this call to
  run the garbage collector.
warning_start_line: 80
