warning_ID: 267
warning_file_name: FlowableRepeatingTransform.java
warning_file_path: src/main/java/com/github/davidmoten/rx2/internal/flowable/FlowableRepeatingTransform.java
warning_repository_URL: https://github.com/davidmoten/rxjava2-extras.git
warning_repository_commit: 0d8e7e5cad69fcb6b9667e48e2cb2d0c90b80813
warning_repository_name: rxjava2-extras
warning_repository_target_java_version: '6'
warning_rule_key: S1948
warning_rule_name: Fields in a "Serializable" class should either be transient or
  serializable
warning_rule_type: Code_Smell
warning_specific_message: Make "destination" transient or serializable.
warning_start_line: 101
