warning_ID: 270
warning_file_name: CommandLineTest.java
warning_file_path: src/test/java/com/adobe/epubcheck/tools/CommandLineTest.java
warning_repository_URL: https://github.com/w3c/epubcheck.git
warning_repository_commit: 794b7ce290c32ea8c3f4a5e4f441aac11fcf2484
warning_repository_name: epubcheck
warning_repository_target_java_version: '7'
warning_rule_key: S4042
warning_rule_name: '"java.nio.Files#delete" should be preferred'
warning_rule_type: Code_Smell
warning_specific_message: Use "java.nio.file.Files#delete" here for better messages
  on error conditions.
warning_start_line: 262
