warning_ID: 271
warning_file_name: FloatLayoutResult.java
warning_file_path: openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/FloatLayoutResult.java
warning_repository_URL: https://github.com/danfickle/openhtmltopdf.git
warning_repository_commit: 0dcb7e4b8c80d0fbf6d21f970ccab7a701221b5d
warning_repository_name: openhtmltopdf
warning_repository_target_java_version: '8'
warning_rule_key: S1134
warning_rule_name: Track uses of "FIXME" tags
warning_rule_type: Code_Smell
warning_specific_message: Take the required action to fix the issue indicated by this
  comment.
warning_start_line: 29
