warning_ID: 273
warning_file_name: SentenceDetectorTest.java
warning_file_path: src/test/java/com/worksap/nlp/sudachi/sentdetect/SentenceDetectorTest.java
warning_repository_URL: https://github.com/WorksApplications/Sudachi.git
warning_repository_commit: 6da3832fda6f6e7da5be419dafd7c0f6be5842f1
warning_repository_name: Sudachi
warning_repository_target_java_version: '8'
warning_rule_key: S4635
warning_rule_name: String offset-based methods should be preferred for finding substrings
  from offsets
warning_rule_type: Code_Smell
warning_specific_message: Replace "startsWith" with the overload that accepts an offset
  parameter.
warning_start_line: 95
