warning_ID: 275
warning_file_name: ZipFileDataSource.java
warning_file_path: src/main/java/org/opentripplanner/datastore/file/ZipFileDataSource.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S5042
warning_rule_name: Expanding archive files without controlling resource consumption
  is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure that expanding this archive file is safe here.
warning_start_line: 82
