warning_ID: 283
warning_file_name: TestLogConfigUtils.java
warning_file_path: singer/src/test/java/com/pinterest/singer/utils/TestLogConfigUtils.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S2737
warning_rule_name: '"catch" clauses should do more than rethrow'
warning_rule_type: Code_Smell
warning_specific_message: Add logic to this catch clause or eliminate it and rethrow
  the exception automatically.
warning_start_line: 189
