warning_ID: 289
warning_file_name: Colors.java
warning_file_path: common/src/main/java/org/movsim/utilities/Colors.java
warning_repository_URL: https://github.com/movsim/movsim.git
warning_repository_commit: 24d4f4b83a7d2e14f16419fbf7ce05cb019c8066
warning_repository_name: movsim
warning_repository_target_java_version: '8'
warning_rule_key: S2183
warning_rule_name: Ints and longs should not be shifted by zero or more than their
  number of bits-1
warning_rule_type: Bug
warning_specific_message: Remove this useless shift
warning_start_line: 10
