warning_ID: 55
warning_file_name: WFG.java
warning_file_path: jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/wfg/WFG.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S1764
warning_rule_name: Identical expressions should not be used on both sides of a binary
  operator
warning_rule_type: Bug
warning_specific_message: Correct one of the identical sub-expressions on both sides
  of operator "-"
warning_start_line: 120
