warning_ID: 56
warning_file_name: DefaultLogStreamProcessor.java
warning_file_path: singer/src/main/java/com/pinterest/singer/processor/DefaultLogStreamProcessor.java
warning_repository_URL: https://github.com/pinterest/singer.git
warning_repository_commit: 67fa012a410a849bf28c22704973a27d8b2eaadf
warning_repository_name: singer
warning_repository_target_java_version: '8'
warning_rule_key: S2676
warning_rule_name: Neither "Math.abs" nor negation should be used on numbers that
  could be "MIN_VALUE"
warning_rule_type: Bug
warning_specific_message: Use the original value instead.
warning_start_line: 314
