warning_ID: 60
warning_file_name: SqlUtils.java
warning_file_path: src/main/java/com/github/vincentrussell/query/mongodb/sql/converter/util/SqlUtils.java
warning_repository_URL: https://github.com/vincentrussell/sql-to-mongo-db-query-converter.git
warning_repository_commit: 961f5c04ef387ee88086908ebacdfb6ef6e3081a
warning_repository_name: sql-to-mongo-db-query-converter
warning_repository_target_java_version: '7'
warning_rule_key: S5857
warning_rule_name: Character classes should be preferred over reluctant quantifiers
  in regular expressions
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of a reluctant quantifier with "[^\\]]++".
warning_start_line: 56
