warning_ID: 68
warning_file_name: TestTokens.java
warning_file_path: test/app/TestTokens.java
warning_repository_URL: https://github.com/ozzi-/JWT4B.git
warning_repository_commit: c1e61531a6f4854eda7b9d8a324c10fc861380db
warning_repository_name: JWT4B
warning_repository_target_java_version: '8'
warning_rule_key: S6418
warning_rule_name: Hard-coded secrets are security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: '''token'' detected in this expression, review this potentially
  hard-coded secret.'
warning_start_line: 7
