warning_ID: 1
warning_file_name: PhraseChecker.java
warning_file_path: src/main/java/simplenlg/aggregation/PhraseChecker.java
warning_repository_URL: https://github.com/simplenlg/simplenlg.git
warning_repository_commit: c65331a528f0241c29051c7a086ae5e9518e07e2
warning_repository_name: simplenlg
warning_repository_target_java_version: '8'
warning_rule_key: S1610
warning_rule_name: Abstract classes without fields should be converted to interfaces
warning_rule_type: Code_Smell
warning_specific_message: Convert the abstract class "PhraseChecker" into an interface.
warning_start_line: 37
