warning_ID: 16
warning_file_name: SecureClientDriverFactoryTest.java
warning_file_path: rest-client-driver/src/test/java/com/github/restdriver/clientdriver/unit/SecureClientDriverFactoryTest.java
warning_repository_URL: https://github.com/rest-driver/rest-driver.git
warning_repository_commit: b4f3dc9797a757d039b5bdd5563058210808d648
warning_repository_name: rest-driver
warning_repository_target_java_version: '8'
warning_rule_key: S6437
warning_rule_name: Credentials should not be hard-coded
warning_rule_type: Vulnerability
warning_specific_message: Revoke and change this password, as it is compromised.
warning_start_line: 101
