warning_ID: 17
warning_file_name: TimingsManager.java
warning_file_path: src/main/java/co/aikar/timings/TimingsManager.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S2160
warning_rule_name: Subclasses that add fields should override "equals"
warning_rule_type: Code_Smell
warning_specific_message: Override the "equals" method in this class.
warning_start_line: 118
