warning_ID: 2
warning_file_name: DB.java
warning_file_path: src/main/java/org/sqlite/core/DB.java
warning_repository_URL: https://github.com/xerial/sqlite-jdbc.git
warning_repository_commit: 6ca62fd07bf7faf58e923ba8651757621ffc693c
warning_repository_name: sqlite-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S1175
warning_rule_name: The signature of "finalize()" should match that of "Object.finalize()"
warning_rule_type: Bug
warning_specific_message: Rename this method to avoid any possible confusion with
  Object.finalize().
warning_start_line: 325
