warning_ID: 4
warning_file_name: EnumAsInner.java
warning_file_path: dataenum-processor/src/test/resources/EnumAsInner.java
warning_repository_URL: https://github.com/spotify/dataenum.git
warning_repository_commit: 7a91307ef55cf9ba94391a4572c9d68dba2c56d5
warning_repository_name: dataenum
warning_repository_target_java_version: '8'
warning_rule_key: S1128
warning_rule_name: Unnecessary imports should be removed
warning_rule_type: Code_Smell
warning_specific_message: 'Remove this unnecessary import: java.lang classes are always
  implicitly imported.'
warning_start_line: 22
