warning_ID: 860
warning_file_name: ConcaveHull.java
warning_file_path: src/main/java/org/opensphere/geometry/algorithm/ConcaveHull.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S1104
warning_rule_name: Class variable fields should not have public accessibility
warning_rule_type: Code_Smell
warning_specific_message: Make shortLengths a static final constant or non-public
  and provide accessors if needed.
warning_start_line: 60
