warning_ID: 861
warning_file_name: ProcessIndividualsForClasses.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/utils/menuManagement/ProcessIndividualsForClasses.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S120
warning_rule_name: Package names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this package name to match the regular expression
  '^[a-z_]+(\.[a-z_][a-z0-9_]*)*$'.
warning_start_line: 3
