warning_ID: 862
warning_file_name: MultiValueEditSubmission.java
warning_file_path: api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/VTwo/MultiValueEditSubmission.java
warning_repository_URL: https://github.com/vivo-project/Vitro.git
warning_repository_commit: 119413413a53cd6ebcbff50d3501f32f72aff6f0
warning_repository_name: Vitro
warning_repository_target_java_version: '8'
warning_rule_key: S6213
warning_rule_name: Restricted Identifiers should not be used as Identifiers
warning_rule_type: Code_Smell
warning_specific_message: Rename this variable to not match a restricted identifier.
warning_start_line: 63
