warning_ID: 866
warning_file_name: Canvas.java
warning_file_path: ascii-render/src/main/java/com/indvd00m/ascii/render/Canvas.java
warning_repository_URL: https://github.com/indvd00m/java-ascii-render.git
warning_repository_commit: 611c08cef73367d6f6d20eb4f8f4721f917a42c6
warning_repository_name: java-ascii-render
warning_repository_target_java_version: '6'
warning_rule_key: S1119
warning_rule_name: Labels should not be used
warning_rule_type: Code_Smell
warning_specific_message: Refactor the code to remove this label and the need for
  it.
warning_start_line: 331
