warning_ID: 869
warning_file_name: TestURLLoader.java
warning_file_path: src/test/java/io/mola/galimatias/TestURLLoader.java
warning_repository_URL: https://github.com/smola/galimatias.git
warning_repository_commit: 0771a10ef5021181fc172b95ac39e9f4c7ada2e8
warning_repository_name: galimatias
warning_repository_target_java_version: '6'
warning_rule_key: S127
warning_rule_name: '"for" loop stop conditions should be invariant'
warning_rule_type: Code_Smell
warning_specific_message: Refactor the code in order to not assign to this loop counter
  from within the loop body.
warning_start_line: 62
