warning_ID: 871
warning_file_name: IdStrategy.java
warning_file_path: protostuff-runtime/src/main/java/io/protostuff/runtime/IdStrategy.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S116
warning_rule_name: Field names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this field "POLYMORPHIC_MAP_PIPE_SCHEMA" to match
  the regular expression '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 143
