warning_ID: 881
warning_file_name: FDA3.java
warning_file_path: jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/fda/FDA3.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S1170
warning_rule_name: Public constants and fields initialized at declaration should be
  "static final" rather than merely "final"
warning_rule_type: Code_Smell
warning_specific_message: Make this final field static too.
warning_start_line: 16
