warning_ID: 902
warning_file_name: MIRACore.java
warning_file_path: src/main/java/org/apache/joshua/mira/MIRACore.java
warning_repository_URL: https://github.com/apache/joshua.git
warning_repository_commit: 716cc81aca318f3cb6ed9bd81bd29f043db77eff
warning_repository_name: joshua
warning_repository_target_java_version: '8'
warning_rule_key: S117
warning_rule_name: Local variable and method parameter names should comply with a
  naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this local variable to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 797
