warning_ID: 922
warning_file_name: Point2D.java
warning_file_path: src/main/java/com/esri/core/geometry/Point2D.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 302
