warning_ID: 926
warning_file_name: RrbTree.java
warning_file_path: src/main/java/org/organicdesign/fp/collections/RrbTree.java
warning_repository_URL: https://github.com/GlenKPeterson/Paguro.git
warning_repository_commit: de98375df2dd9c26a8cb618d51862f52c64602af
warning_repository_name: Paguro
warning_repository_target_java_version: '11'
warning_rule_key: S6355
warning_rule_name: Deprecated annotations should include explanations
warning_rule_type: Code_Smell
warning_specific_message: Add 'since' and/or 'forRemoval' arguments to the @Deprecated
  annotation.
warning_start_line: 1060
