warning_ID: 927
warning_file_name: JUnitReportingRunnerIntegrationTest.java
warning_file_path: src/test/java/com/github/valfirst/jbehave/junit/monitoring/JUnitReportingRunnerIntegrationTest.java
warning_repository_URL: https://github.com/valfirst/jbehave-junit-runner.git
warning_repository_commit: f1295698787525a7ce99cd9a95a4c5cb5277f15f
warning_repository_name: jbehave-junit-runner
warning_repository_target_java_version: '8'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 90
