warning_ID: 941
warning_file_name: QueryingTest.java
warning_file_path: src/test/java/com/shapesecurity/salvation2/QueryingTest.java
warning_repository_URL: https://github.com/shapesecurity/salvation.git
warning_repository_commit: e2b07ea083e1c15415a25391c95c604a23ec9bfb
warning_repository_name: salvation
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "script-src
  wss://a;" 3 times.
warning_start_line: 175
