warning_ID: 948
warning_file_name: Tuple5.java
warning_file_path: src/main/java/com/jnape/palatable/lambda/adt/hlist/Tuple5.java
warning_repository_URL: https://github.com/palatable/lambda.git
warning_repository_commit: 3f23529573f7a2f7f7a11aca3d9d7e720cf2a15b
warning_repository_name: lambda
warning_repository_target_java_version: '8'
warning_rule_key: S119
warning_rule_name: Type parameter names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this generic name to match the regular expression
  '^[A-Z][0-9]?$'.
warning_start_line: 313
