warning_ID: 58
warning_file_name: MavenWrapperDownloader.java
warning_file_path: .mvn/wrapper/MavenWrapperDownloader.java
warning_repository_URL: https://github.com/wstrange/GoogleAuth.git
warning_repository_commit: 5cc0970ed6a269468c5552bbe0268c64012fae8b
warning_repository_name: GoogleAuth
warning_repository_target_java_version: '7'
warning_rule_key: S1181
warning_rule_name: Throwable and Error should not be caught
warning_rule_type: Code_Smell
warning_specific_message: Catch Exception instead of Throwable.
warning_start_line: 90
