warning_ID: 66
warning_file_name: SdsDowngradeDelayService.java
warning_file_path: sds-client/src/main/java/com/didiglobal/sds/client/service/SdsDowngradeDelayService.java
warning_repository_URL: https://github.com/didi/sds.git
warning_repository_commit: 46dac33f39bc1720ca108bd61b6375874906ad57
warning_repository_name: sds
warning_repository_target_java_version: '8'
warning_rule_key: S4065
warning_rule_name: '"ThreadLocal.withInitial" should be preferred'
warning_rule_type: Code_Smell
warning_specific_message: Replace this anonymous class with a call to "ThreadLocal.withInitial".
warning_start_line: 40
