warning_ID: 22
warning_file_name: ExecutionLock.java
warning_file_path: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ExecutionLock.java
warning_repository_URL: https://github.com/alexcojocaru/elasticsearch-maven-plugin.git
warning_repository_commit: 3b1c502b5d784523faec699b7e0a6e37888e9b95
warning_repository_name: elasticsearch-maven-plugin
warning_repository_target_java_version: '8'
warning_rule_key: S2274
warning_rule_name: '"Object.wait(...)" and "Condition.await(...)" should be called
  inside a "while" loop'
warning_rule_type: Code_Smell
warning_specific_message: Remove this call to "wait" or move it into a "while" loop.
warning_start_line: 31
