warning_ID: 23
warning_file_name: EditServiceRecordController.java
warning_file_path: miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditServiceRecordController.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S6213
warning_rule_name: Restricted Identifiers should not be used as Identifiers
warning_rule_type: Code_Smell
warning_specific_message: Rename this variable to not match a restricted identifier.
warning_start_line: 78
