warning_ID: 28
warning_file_name: WorldFilterJson_Biome.java
warning_file_path: src/main/java/amidst/mojangapi/file/json/filter/WorldFilterJson_Biome.java
warning_repository_URL: https://github.com/toolbox4minecraft/amidst.git
warning_repository_commit: 2902ca61aa8f28e2e3cd903a732b5d29da93b9e3
warning_repository_name: amidst
warning_repository_target_java_version: '8'
warning_rule_key: S3077
warning_rule_name: Non-primitive fields should not be "volatile"
warning_rule_type: Bug
warning_specific_message: Use a thread-safe type; adding "volatile" is not enough
  to make this field thread-safe.
warning_start_line: 19
