warning_ID: 32
warning_file_name: ShareSnapshotTests.java
warning_file_path: core-test/src/main/java/org/openstack4j/api/manila/ShareSnapshotTests.java
warning_repository_URL: https://github.com/ContainX/openstack4j.git
warning_repository_commit: 79568cf4991da82192ef27d8f5f0f6195da698ef
warning_repository_name: openstack4j
warning_repository_target_java_version: '7'
warning_rule_key: S1313
warning_rule_name: Using hardcoded IP addresses is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure using this hardcoded IP address is safe here.
warning_start_line: 58
