warning_ID: 36
warning_file_name: ErrorMessageTest.java
warning_file_path: src/test/java/org/sqlite/ErrorMessageTest.java
warning_repository_URL: https://github.com/xerial/sqlite-jdbc.git
warning_repository_commit: 6ca62fd07bf7faf58e923ba8651757621ffc693c
warning_repository_name: sqlite-jdbc
warning_repository_target_java_version: '8'
warning_rule_key: S5445
warning_rule_name: Insecure temporary file creation methods should not be used
warning_rule_type: Vulnerability
warning_specific_message: Use "Files.createTempDirectory" to create this directory
  instead.
warning_start_line: 118
