warning_ID: 43
warning_file_name: NSObject.java
warning_file_path: src/main/java/com/dd/plist/NSObject.java
warning_repository_URL: https://github.com/3breadt/dd-plist.git
warning_repository_commit: 91f8ba7fd92a9a503484a540e5fd3e03f411d98a
warning_repository_name: dd-plist
warning_repository_target_java_version: '8'
warning_rule_key: S2864
warning_rule_name: '"entrySet()" should be iterated when both the key and value are
  needed'
warning_rule_type: Code_Smell
warning_specific_message: Iterate over the "entrySet" instead of the "keySet".
warning_start_line: 375
