warning_ID: 45
warning_file_name: FormattedCommandAlias.java
warning_file_path: src/main/java/cn/nukkit/command/FormattedCommandAlias.java
warning_repository_URL: https://github.com/CloudburstMC/Nukkit.git
warning_repository_commit: 47d54ad26109b5d89936e0d9123c591a99a2cf60
warning_repository_name: Nukkit
warning_repository_target_java_version: '8'
warning_rule_key: S1193
warning_rule_name: Exception types should not be tested using "instanceof" in catch
  blocks
warning_rule_type: Code_Smell
warning_specific_message: Replace the usage of the "instanceof" operator by a catch
  block.
warning_start_line: 37
