warning_ID: 50
warning_file_name: TypeSelectorTypeAdapterFactory.java
warning_file_path: src/main/java/io/gsonfire/gson/TypeSelectorTypeAdapterFactory.java
warning_repository_URL: https://github.com/julman99/gson-fire.git
warning_repository_commit: 5dd4cd703065b0d4127390c6bdec1fb434ebec71
warning_repository_name: gson-fire
warning_repository_target_java_version: '6'
warning_rule_key: S4977
warning_rule_name: Type parameters should not shadow other type parameters
warning_rule_type: Code_Smell
warning_specific_message: Rename "T" which hides a type parameter from the outer scope.
warning_start_line: 44
