warning_ID: 707
warning_file_name: Layer.java
warning_file_path: openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/Layer.java
warning_repository_URL: https://github.com/danfickle/openhtmltopdf.git
warning_repository_commit: 0dcb7e4b8c80d0fbf6d21f970ccab7a701221b5d
warning_repository_name: openhtmltopdf
warning_repository_target_java_version: '8'
warning_rule_key: S1123
warning_rule_name: Deprecated elements should have both the annotation and the Javadoc
  tag
warning_rule_type: Code_Smell
warning_specific_message: Add the missing @deprecated Javadoc tag.
warning_start_line: 883
