warning_ID: 718
warning_file_name: MatchesRegularExpression.java
warning_file_path: src/test/java/com/github/javafaker/matchers/MatchesRegularExpression.java
warning_repository_URL: https://github.com/DiUS/java-faker.git
warning_repository_commit: b60f23a54a511cf7e24c09366b2957219b448125
warning_repository_name: java-faker
warning_repository_target_java_version: '6'
warning_rule_key: S2326
warning_rule_name: Unused type parameters should be removed
warning_rule_type: Code_Smell
warning_specific_message: T is not used in the method.
warning_start_line: 27
