warning_ID: 719
warning_file_name: JUnitScenarioReporter.java
warning_file_path: src/main/java/com/github/valfirst/jbehave/junit/monitoring/JUnitScenarioReporter.java
warning_repository_URL: https://github.com/valfirst/jbehave-junit-runner.git
warning_repository_commit: f1295698787525a7ce99cd9a95a4c5cb5277f15f
warning_repository_name: jbehave-junit-runner
warning_repository_target_java_version: '8'
warning_rule_key: S1871
warning_rule_name: Two branches in a conditional structure should not have exactly
  the same implementation
warning_rule_type: Code_Smell
warning_specific_message: This branch's code block is the same as the block for the
  branch on line 84.
warning_start_line: 90
