warning_ID: 725
warning_file_name: Kcp.java
warning_file_path: kcp-netty/src/main/java/io/jpower/kcp/netty/Kcp.java
warning_repository_URL: https://github.com/szhnet/kcp-netty.git
warning_repository_commit: 9e98603bd11d58c8d1ca88e520670b884c828e04
warning_repository_name: kcp-netty
warning_repository_target_java_version: '8'
warning_rule_key: S1066
warning_rule_name: Collapsible "if" statements should be merged
warning_rule_type: Code_Smell
warning_specific_message: Merge this if statement with the enclosing one.
warning_start_line: 528
