warning_ID: 728
warning_file_name: LineBandTool.java
warning_file_path: modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/tools/LineBandTool.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S2184
warning_rule_name: Math operands should be cast before assignment
warning_rule_type: Bug
warning_specific_message: Cast one of the operands of this subtraction operation to
  a "float".
warning_start_line: 208
