warning_ID: 738
warning_file_name: VueComponentFactoryGenerator.java
warning_file_path: processors/src/main/java/com/axellience/vuegwt/processors/component/factory/VueComponentFactoryGenerator.java
warning_repository_URL: https://github.com/VueGWT/vue-gwt.git
warning_repository_commit: dc818e0ac31c4fd4254065b50a1d7c59f291ca9d
warning_repository_name: vue-gwt
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "componentOptions"
  3 times.
warning_start_line: 90
