warning_ID: 739
warning_file_name: IndexHashTable.java
warning_file_path: src/main/java/com/esri/core/geometry/IndexHashTable.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S1221
warning_rule_name: Methods should not be named "tostring", "hashcode" or "equal"
warning_rule_type: Bug
warning_specific_message: Either override Object.equals(Object obj), or totally rename
  the method to prevent any confusion.
warning_start_line: 38
