warning_ID: 292
warning_file_name: TopicSpanNameTest.java
warning_file_path: opentracing-kafka-client/src/test/java/io/opentracing/contrib/kafka/TopicSpanNameTest.java
warning_repository_URL: https://github.com/opentracing-contrib/java-kafka-client.git
warning_repository_commit: 25058dac357b206e599d69d9f444494d13547737
warning_repository_name: java-kafka-client
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "receive"
  6 times.
warning_start_line: 39
