warning_ID: 315
warning_file_name: JWTSuiteTab.java
warning_file_path: src/gui/JWTSuiteTab.java
warning_repository_URL: https://github.com/ozzi-/JWT4B.git
warning_repository_commit: c1e61531a6f4854eda7b9d8a324c10fc861380db
warning_repository_name: JWT4B
warning_repository_target_java_version: '8'
warning_rule_key: S117
warning_rule_name: Local variable and method parameter names should comply with a
  naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this local variable to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 226
