warning_ID: 316
warning_file_name: CompressedReaderTest.java
warning_file_path: src/test/java/com/spotify/sparkey/CompressedReaderTest.java
warning_repository_URL: https://github.com/spotify/sparkey-java.git
warning_repository_commit: c829bab45abf9cba3d017b798efe9ef5f0effbb3
warning_repository_name: sparkey-java
warning_repository_target_java_version: '8'
warning_rule_key: S1130
warning_rule_name: '"throws" declarations should not be superfluous'
warning_rule_type: Code_Smell
warning_specific_message: Remove the declaration of thrown exception 'java.io.IOException',
  as it cannot be thrown from constructor's body.
warning_start_line: 18
