warning_ID: 320
warning_file_name: URLFactory.java
warning_file_path: src/main/java/com/networknt/schema/uri/URLFactory.java
warning_repository_URL: https://github.com/networknt/json-schema-validator.git
warning_repository_commit: 6cb431f82b41530c35c14f4430e11f3051d82d73
warning_repository_name: json-schema-validator
warning_repository_target_java_version: '8'
warning_rule_key: S2147
warning_rule_name: Catches should be combined
warning_rule_type: Code_Smell
warning_specific_message: Combine this catch with the one at line 44, which has the
  same body.
warning_start_line: 46
