warning_ID: 325
warning_file_name: CustomerResourceTest.java
warning_file_path: oreilly-jaxrs-2.0-workbook/ex10_1/src/test/java/com/restfully/shop/test/CustomerResourceTest.java
warning_repository_URL: https://github.com/resteasy/resteasy-examples.git
warning_repository_commit: 6b52d7f6c16a291d3c8348fe09697b5fc86ba153
warning_repository_name: resteasy-examples
warning_repository_target_java_version: '8'
warning_rule_key: S106
warning_rule_name: Standard outputs should not be used directly to log anything
warning_rule_type: Code_Smell
warning_specific_message: Replace this use of System.out or System.err by a logger.
warning_start_line: 43
