warning_ID: 326
warning_file_name: AbstractUnmodSet.java
warning_file_path: src/main/java/org/organicdesign/fp/collections/AbstractUnmodSet.java
warning_repository_URL: https://github.com/GlenKPeterson/Paguro.git
warning_repository_commit: de98375df2dd9c26a8cb618d51862f52c64602af
warning_repository_name: Paguro
warning_repository_target_java_version: '11'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 13
