warning_ID: 329
warning_file_name: PiwikRequestTest.java
warning_file_path: src/test/java/org/piwik/java/tracking/PiwikRequestTest.java
warning_repository_URL: https://github.com/matomo-org/matomo-java-tracker.git
warning_repository_commit: a1dbaae91944c5185da03c5b67e2640a7349a4c4
warning_repository_name: matomo-java-tracker
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 294
