warning_ID: 355
warning_file_name: SimpleServer.java
warning_file_path: src/main/java/simplenlg/server/SimpleServer.java
warning_repository_URL: https://github.com/simplenlg/simplenlg.git
warning_repository_commit: c65331a528f0241c29051c7a086ae5e9518e07e2
warning_repository_name: simplenlg
warning_repository_target_java_version: '8'
warning_rule_key: S1141
warning_rule_name: Try-catch blocks should not be nested
warning_rule_type: Code_Smell
warning_specific_message: Extract this nested try block into a separate method.
warning_start_line: 244
