warning_ID: 360
warning_file_name: NfeConsultaStub.java
warning_file_path: src/main/java/com/fincatto/documentofiscal/nfe310/webservices/nota/consulta/NfeConsultaStub.java
warning_repository_URL: https://github.com/wmixvideo/nfe.git
warning_repository_commit: d0b2ce5ea0749448b1b3dbb9bef88d7eccd05240
warning_repository_name: nfe
warning_repository_target_java_version: '8'
warning_rule_key: S1149
warning_rule_name: Synchronized classes Vector, Hashtable, Stack and StringBuffer
  should not be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the synchronized class "Vector" by an unsynchronized
  one such as "ArrayList" or "LinkedList".
warning_start_line: 1362
