warning_ID: 368
warning_file_name: RelationalOperations.java
warning_file_path: src/main/java/com/esri/core/geometry/RelationalOperations.java
warning_repository_URL: https://github.com/Esri/geometry-api-java.git
warning_repository_commit: a1af6612f4de7fc1baee1c331c335f154a4a96c9
warning_repository_name: geometry-api-java
warning_repository_target_java_version: '7'
warning_rule_key: S3776
warning_rule_name: Cognitive Complexity of methods should not be too high
warning_rule_type: Code_Smell
warning_specific_message: Refactor this method to reduce its Cognitive Complexity
  from 28 to the 15 allowed.
warning_start_line: 4139
