warning_ID: 372
warning_file_name: PullConsumerApp.java
warning_file_path: openmessaging-api-samples/src/main/java/io/openmessaging/samples/consumer/PullConsumerApp.java
warning_repository_URL: https://github.com/openmessaging/openmessaging-java.git
warning_repository_commit: d8262897fb98e2d75d39e189bff763a25563e9f2
warning_repository_name: openmessaging-java
warning_repository_target_java_version: '8'
warning_rule_key: S1604
warning_rule_name: Anonymous inner classes containing only one method should become
  lambdas
warning_rule_type: Code_Smell
warning_specific_message: Make this anonymous inner class a lambda
warning_start_line: 36
