warning_ID: 373
warning_file_name: HasFieldOfGenericType.java
warning_file_path: src/test/benchmarks/org/mutabilitydetector/benchmarks/mutabletofield/generic/HasFieldOfGenericType.java
warning_repository_URL: https://github.com/MutabilityDetector/MutabilityDetector.git
warning_repository_commit: ac1bc226e109b21bf92e74dd76d77e2f1a6a929d
warning_repository_name: MutabilityDetector
warning_repository_target_java_version: '8'
warning_rule_key: S1948
warning_rule_name: Fields in a "Serializable" class should either be transient or
  serializable
warning_rule_type: Code_Smell
warning_specific_message: Make "fieldOfN" transient or serializable.
warning_start_line: 31
