warning_ID: 377
warning_file_name: MsgpackSimpleTest.java
warning_file_path: protostuff-msgpack/src/test/java/io/protostuff/MsgpackSimpleTest.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S1764
warning_rule_name: Identical expressions should not be used on both sides of a binary
  operator
warning_rule_type: Bug
warning_specific_message: Correct one of the identical sub-expressions on both sides
  of operator "-"
warning_start_line: 77
