warning_ID: 378
warning_file_name: Queries.java
warning_file_path: src/main/java/com/github/davidmoten/rx/jdbc/Queries.java
warning_repository_URL: https://github.com/davidmoten/rxjava-jdbc.git
warning_repository_commit: e62609a10fb144debd2b3b833f02474c01cc5b81
warning_repository_name: rxjava-jdbc
warning_repository_target_java_version: '7'
warning_rule_key: S2293
warning_rule_name: The diamond operator ("<>") should be used
warning_rule_type: Code_Smell
warning_specific_message: Replace the type specification in this constructor call
  with the diamond operator ("<>").
warning_start_line: 26
