warning_ID: 380
warning_file_name: MetricsStream.java
warning_file_path: wls-exporter-core/src/main/java/com/oracle/wls/exporter/MetricsStream.java
warning_repository_URL: https://github.com/oracle/weblogic-monitoring-exporter.git
warning_repository_commit: 9d17454fd9e34f05acbf942418c3a92ef40fdec1
warning_repository_name: weblogic-monitoring-exporter
warning_repository_target_java_version: '8'
warning_rule_key: S3457
warning_rule_name: Printf-style format strings should be used correctly
warning_rule_type: Code_Smell
warning_specific_message: '%n should be used in place of \n to produce the platform-specific
  line separator.'
warning_start_line: 72
