warning_ID: 387
warning_file_name: JsonParserTest.java
warning_file_path: src/test/java/com/grack/nanojson/JsonParserTest.java
warning_repository_URL: https://github.com/mmastrac/nanojson.git
warning_repository_commit: c31d4029fb2f43f5bd4c5dfba5d53f626360af71
warning_repository_name: nanojson
warning_repository_target_java_version: '7'
warning_rule_key: S1488
warning_rule_name: Local variables should not be declared and then immediately returned
  or thrown
warning_rule_type: Code_Smell
warning_specific_message: Immediately return this expression instead of assigning
  it to the temporary variable "s".
warning_start_line: 929
