ai_name: CodeCureAgent
warning_ID: 35
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_target_java_version: 6
warning_rule_key: S1319
warning_file_path: src/main/java/org/junit/runner/Description.java
warning_start_line: 200
warning_rule_name: >-
  Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"
warning_specific_message: >-
  The return type of this method should be an interface such as "List" rather than the implementation "ArrayList".
warning_rule_type: Code_Smell
