warning_ID: 750
warning_file_name: PolymorphicMapSchema.java
warning_file_path: protostuff-runtime/src/main/java/io/protostuff/runtime/PolymorphicMapSchema.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S112
warning_rule_name: Generic exceptions should never be thrown
warning_rule_type: Code_Smell
warning_specific_message: Define and throw a dedicated exception instead of using
  a generic one.
warning_start_line: 402
