warning_ID: 751
warning_file_name: MapCommandTest.java
warning_file_path: aesh/src/test/java/org/aesh/command/map/MapCommandTest.java
warning_repository_URL: https://github.com/aeshell/aesh.git
warning_repository_commit: cfebb087dc3c2b580bb4c64a46333243a9497192
warning_repository_name: aesh
warning_repository_target_java_version: '8'
warning_rule_key: S1170
warning_rule_name: Public constants and fields initialized at declaration should be
  "static final" rather than merely "final"
warning_rule_type: Code_Smell
warning_specific_message: Make this final field static too.
warning_start_line: 53
