warning_ID: 757
warning_file_name: Environment.java
warning_file_path: src/main/java/org/opentripplanner/visibility/Environment.java
warning_repository_URL: https://github.com/opentripplanner/OpenTripPlanner.git
warning_repository_commit: cc7de54e949771dca9cb7e91b1f0456ae141e9b6
warning_repository_name: OpenTripPlanner
warning_repository_target_java_version: '11'
warning_rule_key: S125
warning_rule_name: Sections of code should not be commented out
warning_rule_type: Code_Smell
warning_specific_message: This block of commented-out lines of code should be removed.
warning_start_line: 90
