warning_ID: 777
warning_file_name: GsonFireBuilder.java
warning_file_path: src/main/java/io/gsonfire/GsonFireBuilder.java
warning_repository_URL: https://github.com/julman99/gson-fire.git
warning_repository_commit: 5dd4cd703065b0d4127390c6bdec1fb434ebec71
warning_repository_name: gson-fire
warning_repository_target_java_version: '6'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 28
