warning_ID: 778
warning_file_name: UpdateMojoTest.java
warning_file_path: license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UpdateMojoTest.java
warning_repository_URL: https://github.com/mycila/license-maven-plugin.git
warning_repository_commit: 690a43fac1629c2e1f8be424e3b658d92496bfdf
warning_repository_name: license-maven-plugin
warning_repository_target_java_version: '8'
warning_rule_key: S3599
warning_rule_name: Double Brace Initialization should not be used
warning_rule_type: Bug
warning_specific_message: Use another way to initialize this instance.
warning_start_line: 128
