warning_ID: 782
warning_file_name: Ebes.java
warning_file_path: jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/ebes/Ebes.java
warning_repository_URL: https://github.com/jMetal/jMetal.git
warning_repository_commit: 96751e81882a5c3289d35106eb240cf0f577782d
warning_repository_name: jMetal
warning_repository_target_java_version: '11'
warning_rule_key: S116
warning_rule_name: Field names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this field "VAR_eZ_UPPER_LIMIT" to match the regular
  expression '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 575
