warning_ID: 788
warning_file_name: SegmentNodeList.java
warning_file_path: modules/core/src/main/java/org/locationtech/jts/noding/SegmentNodeList.java
warning_repository_URL: https://github.com/locationtech/jts.git
warning_repository_commit: 402acb6e4d8cfb0a1de061811455564176483288
warning_repository_name: jts
warning_repository_target_java_version: '8'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 91
