warning_ID: 794
warning_file_name: ModelFactory.java
warning_file_path: core/src/main/java/com/tobedevoured/modelcitizen/ModelFactory.java
warning_repository_URL: https://github.com/mguymon/model-citizen.git
warning_repository_commit: 5d7f40e08de506f489852c4e5cbcd181ee47f704
warning_repository_name: model-citizen
warning_repository_target_java_version: '6'
warning_rule_key: S3740
warning_rule_name: Raw types should not be used
warning_rule_type: Code_Smell
warning_specific_message: Provide the parametrized type for this generic.
warning_start_line: 696
