warning_ID: 797
warning_file_name: DefaultClientDriverJettyHandlerTest.java
warning_file_path: rest-client-driver/src/test/java/com/github/restdriver/clientdriver/jetty/DefaultClientDriverJettyHandlerTest.java
warning_repository_URL: https://github.com/rest-driver/rest-driver.git
warning_repository_commit: b4f3dc9797a757d039b5bdd5563058210808d648
warning_repository_name: rest-driver
warning_repository_target_java_version: '8'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 75
