warning_ID: 798
warning_file_name: ValidationUtils.java
warning_file_path: miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/ValidationUtils.java
warning_repository_URL: https://github.com/miso-lims/miso-lims.git
warning_repository_commit: c2f31c47fef39ae844c66904fa0d8f4df804a524
warning_repository_name: miso-lims
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Define a constant instead of duplicating this literal "detailedQcStatusNote"
  3 times.
warning_start_line: 79
