warning_ID: 806
warning_file_name: RecognisedVersion.java
warning_file_path: src/main/java/amidst/mojangapi/minecraftinterface/RecognisedVersion.java
warning_repository_URL: https://github.com/toolbox4minecraft/amidst.git
warning_repository_commit: 2902ca61aa8f28e2e3cd903a732b5d29da93b9e3
warning_repository_name: amidst
warning_repository_target_java_version: '8'
warning_rule_key: S115
warning_rule_name: Constant names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this constant name to match the regular expression
  '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
warning_start_line: 50
