warning_ID: 812
warning_file_name: MapSchema.java
warning_file_path: protostuff-collectionschema/src/main/java/io/protostuff/MapSchema.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S1854
warning_rule_name: Unused assignments should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this useless assignment to local variable "!unknown!".
warning_start_line: 394
