warning_ID: 817
warning_file_name: DatamodelConverter.java
warning_file_path: wdtk-datamodel/src/main/java/org/wikidata/wdtk/datamodel/helpers/DatamodelConverter.java
warning_repository_URL: https://github.com/Wikidata/Wikidata-Toolkit.git
warning_repository_commit: 8400cdd50528f0d21eea93bacf5998ba950b30ce
warning_repository_name: Wikidata-Toolkit
warning_repository_target_java_version: '8'
warning_rule_key: S1133
warning_rule_name: Deprecated code should be removed
warning_rule_type: Code_Smell
warning_specific_message: Do not forget to remove this deprecated code someday.
warning_start_line: 175
