warning_ID: 821
warning_file_name: Base64.java
warning_file_path: src/main/java/com/dd/plist/Base64.java
warning_repository_URL: https://github.com/3breadt/dd-plist.git
warning_repository_commit: 91f8ba7fd92a9a503484a540e5fd3e03f411d98a
warning_repository_name: dd-plist
warning_repository_target_java_version: '8'
warning_rule_key: S1192
warning_rule_name: String literals should not be duplicated
warning_rule_type: Code_Smell
warning_specific_message: Use already-defined constant 'PREFERRED_ENCODING' instead
  of duplicating its value here.
warning_start_line: 1649
