warning_ID: 827
warning_file_name: IOUtil.java
warning_file_path: src/main/java/org/nlpcn/commons/lang/util/IOUtil.java
warning_repository_URL: https://github.com/NLPchina/nlp-lang.git
warning_repository_commit: a501d574fdac7b0be76b2d6465a549db73597d6e
warning_repository_name: nlp-lang
warning_repository_target_java_version: '8'
warning_rule_key: S4507
warning_rule_name: Delivering code in production with debug features activated is
  security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure this debug feature is deactivated before delivering
  the code in production.
warning_start_line: 191
