warning_ID: 848
warning_file_name: EmptyMessageIT.java
warning_file_path: protostuff-it/src/test/java/io/protostuff/compiler/java_bean/EmptyMessageIT.java
warning_repository_URL: https://github.com/protostuff/protostuff.git
warning_repository_commit: eb32eaabd397e7a90eb799ead13eda4d6ea8d1d0
warning_repository_name: protostuff
warning_repository_target_java_version: '7'
warning_rule_key: S100
warning_rule_name: Method names should comply with a naming convention
warning_rule_type: Code_Smell
warning_specific_message: Rename this method name to match the regular expression
  '^[a-z][a-zA-Z0-9]*$'.
warning_start_line: 56
