warning_ID: 34
warning_file_name: ProxyServletTest.java
warning_file_path: src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java
warning_repository_URL: https://github.com/mitre/HTTP-Proxy-Servlet.git
warning_repository_commit: 34edf588ad9a02fecffe5efbad0d42ec592838ae
warning_repository_name: HTTP-Proxy-Servlet
warning_rule_key: S1313
warning_rule_name: Using hardcoded IP addresses is security-sensitive
warning_rule_type: Security_Hotspot
warning_specific_message: Make sure using this hardcoded IP address is safe here.
warning_start_line: 234
