warning_ID: 35
warning_file_name: Description.java
warning_file_path: src/main/java/org/junit/runner/Description.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1319
warning_rule_name: Declarations should use Java collection interfaces such as "List"
  rather than specific implementation classes such as "LinkedList"
warning_rule_type: Code_Smell
warning_specific_message: The return type of this method should be an interface such
  as "List" rather than the implementation "ArrayList".
warning_start_line: 200
