warning_ID: 37
warning_file_name: WithExtendedParameterSources.java
warning_file_path: src/test/java/org/junit/tests/experimental/theories/runner/WithExtendedParameterSources.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1444
warning_rule_name: '"public static" fields should be constant'
warning_rule_type: Code_Smell
warning_specific_message: Make this "public static log" field final
warning_start_line: 109
