warning_ID: 39
warning_file_name: ParameterizedTestTest.java
warning_file_path: src/test/java/org/junit/tests/running/classes/ParameterizedTestTest.java
warning_repository_URL: https://github.com/junit-team/junit4.git
warning_repository_commit: 7852b90cfe1cea1e0cdaa19d490c83f0d8684b50
warning_repository_name: junit4
warning_rule_key: S1452
warning_rule_name: Generic wildcard types should not be used in return types
warning_rule_type: Code_Smell
warning_specific_message: Remove usage of generic wildcard type.
warning_start_line: 641
