warning_ID: 40
warning_file_name: ProxyServletTest.java
warning_file_path: src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java
warning_repository_URL: https://github.com/mitre/HTTP-Proxy-Servlet.git
warning_repository_commit: 34edf588ad9a02fecffe5efbad0d42ec592838ae
warning_repository_name: HTTP-Proxy-Servlet
warning_rule_key: S1481
warning_rule_name: Unused local variables should be removed
warning_rule_type: Code_Smell
warning_specific_message: Remove this unused "rsp" local variable.
warning_start_line: 235
